#pragma once

/** Umbrella include for the entity–component–signal layer. */

#include "spark/ecs/GameComponent.hpp"
#include "spark/ecs/GameObject.hpp"
#include "spark/ecs/Signal.hpp"
#include "spark/ecs/components/CollisionComponent.hpp"
#include "spark/ecs/components/AnimatorComponent.hpp"
#include "spark/ecs/components/Character3DAnimFsmComponent.hpp"
#include "spark/ecs/components/MaterialComponent.hpp"
#include "spark/ecs/components/MeshComponent.hpp"
#include "spark/ecs/components/PointLightComponent.hpp"
#include "spark/ecs/components/SkinnedMeshComponent.hpp"
#include "spark/ecs/components/TextOverlayComponent.hpp"
#include "spark/ecs/components/GuiCanvasComponent.hpp"
#include "spark/ecs/components/SkyComponent.hpp"
#include "spark/ecs/components/ParticleEmitterComponent.hpp"
#include "spark/ecs/components/TerrainComponent.hpp"
#include "spark/ecs/components/TransformComponent.hpp"
#include "spark/ecs/components/BoxCollider2DComponent.hpp"
#include "spark/ecs/components/CircleCollider2DComponent.hpp"
#include "spark/ecs/components/SpriteLighting2DComponent.hpp"
#include "spark/ecs/components/Rigidbody2DComponent.hpp"
#include "spark/ecs/components/BoxCollider3DComponent.hpp"
#include "spark/ecs/components/SphereCollider3DComponent.hpp"
#include "spark/ecs/components/Rigidbody3DComponent.hpp"
#include "spark/ecs/components/PhysicsMaterial3DComponent.hpp"
#include "spark/ecs/components/DistanceJoint3DComponent.hpp"
#include "spark/ecs/components/SceneSpatialPolicyComponent.hpp"
#include "spark/ecs/components/SoundCueComponent.hpp"
