/* <auto-generated /> — SPARK_SCRIPT_BIND. Do not edit. */
#pragma once
/* Included from SparkInterop.h inside extern "C" — do not wrap linkage here. */

SPARK_SCRIPT_API int spark_ai_agent_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ai_agent_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API int spark_ai_agent_is_fsm_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ai_agent_set_fsm_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API float spark_ai_agent_get_max_speed(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ai_agent_set_max_speed(SparkGameComponent* component, float s);
SPARK_SCRIPT_API int spark_ai_agent_get_steering_plane(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ai_agent_set_steering_plane(SparkGameComponent* component, int p);
SPARK_SCRIPT_API int spark_ai_agent_is_goap_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ai_agent_set_goap_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API uint64_t spark_ai_agent_get_goap_world_bits(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ai_agent_set_goap_world_bits(SparkGameComponent* component, uint64_t w);
SPARK_SCRIPT_API uint64_t spark_ai_agent_get_goap_goal_mask(const SparkGameComponent* component);
SPARK_SCRIPT_API uint64_t spark_ai_agent_get_goap_goal_value(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_ai_agent_get_path_index(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ai_agent_set_path_index(SparkGameComponent* component, int i);
SPARK_SCRIPT_API int spark_ai_agent_is_fuzzy_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ai_agent_set_fuzzy_enabled(SparkGameComponent* component, int e);

SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grid_nav_agent2_d_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_grid_source_object(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_goal_mode(SparkGameComponent* component, int mode);
SPARK_SCRIPT_API int spark_grid_nav_agent2_d_get_goal_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_goal_target(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_goal_world_position(SparkGameComponent* component, const SparkVector2* position);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_get_goal_world_position(const SparkGameComponent* component, SparkVector2* outGoalWorldPosition);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_repath_every_frame(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grid_nav_agent2_d_get_repath_every_frame(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_repath_interval_seconds(SparkGameComponent* component, float seconds);
SPARK_SCRIPT_API float spark_grid_nav_agent2_d_get_repath_interval_seconds(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_sync_to_ai_agent(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grid_nav_agent2_d_get_sync_to_ai_agent(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_request_repath(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_clear_path(SparkGameComponent* component);
SPARK_SCRIPT_API int spark_grid_nav_agent2_d_has_s_path(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_grid_nav_agent2_d_get_path_index(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_nav_agent2_d_set_path_index(SparkGameComponent* component, int index);

SPARK_SCRIPT_API void spark_grid_nav_target2_d_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grid_nav_target2_d_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_nav_target2_d_set_snap_to_walkable_cell(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grid_nav_target2_d_get_snap_to_walkable_cell(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_grid_path_follower2_d_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grid_path_follower2_d_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_path_follower2_d_set_mode(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grid_path_follower2_d_get_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_path_follower2_d_set_max_speed(SparkGameComponent* component, float speed);
SPARK_SCRIPT_API float spark_grid_path_follower2_d_get_max_speed(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_path_follower2_d_set_arrive_radius(SparkGameComponent* component, float radius);
SPARK_SCRIPT_API float spark_grid_path_follower2_d_get_arrive_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grid_path_follower2_d_set_stop_on_path_end(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grid_path_follower2_d_get_stop_on_path_end(const SparkGameComponent* component);

SPARK_SCRIPT_API int spark_nav_mesh_agent_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_nav_mesh_agent_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API void spark_nav_mesh_agent_set_patrol_path_object(SparkGameComponent* component, SparkGameObject* o);
SPARK_SCRIPT_API int spark_nav_mesh_agent_is_use_grid_pathfinding(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_nav_mesh_agent_set_use_grid_pathfinding(SparkGameComponent* component, int u);
SPARK_SCRIPT_API void spark_nav_mesh_agent_get_grid_origin_x_z(const SparkGameComponent* component, SparkVector2* outGridOriginXZ);
SPARK_SCRIPT_API void spark_nav_mesh_agent_set_grid_origin_x_z(SparkGameComponent* component, const SparkVector2* o);
SPARK_SCRIPT_API float spark_nav_mesh_agent_get_grid_cell_size(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_nav_mesh_agent_set_grid_cell_size(SparkGameComponent* component, float s);
SPARK_SCRIPT_API int32_t spark_nav_mesh_agent_get_grid_width(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_nav_mesh_agent_set_grid_width(SparkGameComponent* component, int32_t w);
SPARK_SCRIPT_API int32_t spark_nav_mesh_agent_get_grid_height(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_nav_mesh_agent_set_grid_height(SparkGameComponent* component, int32_t h);

SPARK_SCRIPT_API int spark_patrol_path_is_looping(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_patrol_path_set_looping(SparkGameComponent* component, int l);
SPARK_SCRIPT_API float spark_patrol_path_get_wait_seconds_per_point(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_patrol_path_set_wait_seconds_per_point(SparkGameComponent* component, float s);

SPARK_SCRIPT_API int spark_perception_sensor_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_perception_sensor_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API float spark_perception_sensor_get_sight_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_perception_sensor_set_sight_radius(SparkGameComponent* component, float r);
SPARK_SCRIPT_API float spark_perception_sensor_get_hearing_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_perception_sensor_set_hearing_radius(SparkGameComponent* component, float r);
SPARK_SCRIPT_API float spark_perception_sensor_get_sight_fov_degrees(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_perception_sensor_set_sight_fov_degrees(SparkGameComponent* component, float d);
SPARK_SCRIPT_API void spark_perception_sensor_set_target_category_mask(SparkGameComponent* component, int m);
SPARK_SCRIPT_API void spark_perception_sensor_clear_detected(SparkGameComponent* component);

SPARK_SCRIPT_API int spark_aim_ik_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_aim_ik_get_weight(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_aim_ik_is_uses_main_camera(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_aim_ik_get_world_target(const SparkGameComponent* component, SparkVector3* outWorldTarget);
SPARK_SCRIPT_API void spark_aim_ik_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API void spark_aim_ik_set_weight(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_aim_ik_set_use_main_camera(SparkGameComponent* component, int value);
SPARK_SCRIPT_API void spark_aim_ik_set_target_object(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_aim_ik_set_world_target(SparkGameComponent* component, const SparkVector3* target);

SPARK_SCRIPT_API void spark_anim_event_receiver_add_marker(SparkGameComponent* component, uint32_t clipIndex, float normalizedTime, const char* eventName);

SPARK_SCRIPT_API void spark_animation_event_vfx_clear_bindings(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_animation_event_vfx_add_binding(SparkGameComponent* component, const char* eventName, const char* vfxAssetKey);
SPARK_SCRIPT_API void spark_animation_event_vfx_set_world_offset(SparkGameComponent* component, const SparkVector3* offset);
SPARK_SCRIPT_API void spark_animation_event_vfx_get_world_offset(const SparkGameComponent* component, SparkVector3* outWorldOffset);

SPARK_SCRIPT_API void spark_animation_hitbox2_d_set_shape(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_animation_hitbox2_d_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_set_clip_index(SparkGameComponent* component, uint32_t index);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_set_start_local_frame(SparkGameComponent* component, uint32_t frame);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_set_end_local_frame(SparkGameComponent* component, uint32_t frame);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_set_local_offset(SparkGameComponent* component, const SparkVector2* offset);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_set_radius(SparkGameComponent* component, float radius);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_set_arc_half_angle_radians(SparkGameComponent* component, float radians);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_set_damage_per_hit(SparkGameComponent* component, float amount);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_clear_targets(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_animation_hitbox2_d_add_target(SparkGameComponent* component, SparkGameObject* target);
SPARK_SCRIPT_API int spark_animation_hitbox2_d_is_hit_window_active(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_animation_hitbox2_d_get_hits_this_swing(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_animation_melee_hit_set_start_event_name(SparkGameComponent* component, const char* name);
SPARK_SCRIPT_API void spark_animation_melee_hit_set_end_event_name(SparkGameComponent* component, const char* name);
SPARK_SCRIPT_API void spark_animation_melee_hit_set_facing_object(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_animation_melee_hit_set_origin_local_offset(SparkGameComponent* component, const SparkVector3* offset);
SPARK_SCRIPT_API void spark_animation_melee_hit_set_trace_distance(SparkGameComponent* component, float meters);
SPARK_SCRIPT_API void spark_animation_melee_hit_set_hit_radius(SparkGameComponent* component, float meters);
SPARK_SCRIPT_API void spark_animation_melee_hit_set_damage_per_hit(SparkGameComponent* component, float amount);
SPARK_SCRIPT_API void spark_animation_melee_hit_clear_targets(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_animation_melee_hit_add_target(SparkGameComponent* component, SparkGameObject* target);
SPARK_SCRIPT_API int spark_animation_melee_hit_is_hit_window_active(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_animation_melee_hit_get_hits_this_swing(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_animation_melee_hit_get_total_hits(const SparkGameComponent* component);

SPARK_SCRIPT_API int spark_char_3d_fsm_is_locomotion_blend_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_char_3d_fsm_is_locomotion_driving_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_char_3d_fsm_is_manual_clip_active(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_char_3d_fsm_get_idle_clip_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_char_3d_fsm_get_walk_clip_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_char_3d_fsm_get_run_clip_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_char_3d_fsm_get_attack_clip_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_char_3d_fsm_get_hurt_clip_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_char_3d_fsm_get_stagger_clip_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_char_3d_fsm_get_death_clip_index(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_char_3d_fsm_get_walk_speed_threshold(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_char_3d_fsm_get_run_speed_threshold(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_char_3d_fsm_get_crossfade_duration(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_char_3d_fsm_get_manual_clip_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_char_3d_fsm_get_manual_clip_loop_mode(const SparkGameComponent* component);

SPARK_SCRIPT_API int spark_foot_ik_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_foot_ik_get_weight(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_foot_ik_get_ray_origin_lift(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_foot_ik_get_ray_max_distance(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_foot_ik_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API void spark_foot_ik_set_weight(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_foot_ik_set_ray_origin_lift(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_foot_ik_set_ray_max_distance(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_foot_ik_set_left_foot_patterns(SparkGameComponent* component, const char* rootPattern, const char* midPattern, const char* endPattern);
SPARK_SCRIPT_API void spark_foot_ik_set_right_foot_patterns(SparkGameComponent* component, const char* rootPattern, const char* midPattern, const char* endPattern);

SPARK_SCRIPT_API void spark_root_motion_set_animator_object(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_root_motion_set_apply_target(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_root_motion_set_facing_object(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_root_motion_set_skeleton_space_scale(SparkGameComponent* component, float scale);
SPARK_SCRIPT_API float spark_root_motion_get_skeleton_space_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_root_motion_set_in_place(SparkGameComponent* component, int enabled);
SPARK_SCRIPT_API int spark_root_motion_is_in_place(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_root_motion_set_enabled(SparkGameComponent* component, int enabled);
SPARK_SCRIPT_API int spark_root_motion_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_root_motion_set_translation_mask(SparkGameComponent* component, int mask);
SPARK_SCRIPT_API int spark_root_motion_get_translation_mask(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_root_motion_set_motion_joint_index(SparkGameComponent* component, uint32_t jointIndex);
SPARK_SCRIPT_API void spark_root_motion_use_pattern_motion_joint_resolver(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_root_motion_get_last_delta_skeleton_space(const SparkGameComponent* component, SparkVector3* outLastDeltaSkeletonSpace);
SPARK_SCRIPT_API void spark_root_motion_get_last_delta_world_space(const SparkGameComponent* component, SparkVector3* outLastDeltaWorldSpace);

SPARK_SCRIPT_API int spark_skeleton_debug_draw_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_skeleton_debug_draw_get_line_color(const SparkGameComponent* component, SparkVector3* outLineColor);
SPARK_SCRIPT_API float spark_skeleton_debug_draw_get_bone_thickness(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_skeleton_debug_draw_get_joint_marker_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_skeleton_debug_draw_set_source_object(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_skeleton_debug_draw_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API void spark_skeleton_debug_draw_toggle_enabled(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_skeleton_debug_draw_set_line_color(SparkGameComponent* component, const SparkVector3* rgb);
SPARK_SCRIPT_API void spark_skeleton_debug_draw_set_bone_thickness(SparkGameComponent* component, float thickness);
SPARK_SCRIPT_API void spark_skeleton_debug_draw_set_joint_marker_scale(SparkGameComponent* component, float scale);

SPARK_SCRIPT_API int32_t spark_skinned_animation_budget_get_max_palette_updates_per_frame(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_skinned_animation_budget_get_max_skinned_draws_per_frame(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_skinned_animation_budget_is_palette_cache_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_skinned_animation_budget_get_palette_quantization_hz(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_skinned_animation_budget_set_max_palette_updates_per_frame(SparkGameComponent* component, uint32_t limit);
SPARK_SCRIPT_API void spark_skinned_animation_budget_set_max_skinned_draws_per_frame(SparkGameComponent* component, uint32_t limit);
SPARK_SCRIPT_API void spark_skinned_animation_budget_set_palette_cache_enabled(SparkGameComponent* component, int enabled);
SPARK_SCRIPT_API void spark_skinned_animation_budget_set_palette_quantization_hz(SparkGameComponent* component, float hz);

SPARK_SCRIPT_API void spark_sprite_2d_fsm_set_combat_blackboard_int_slot(SparkGameComponent* component, int slotOrMax);

SPARK_SCRIPT_API void spark_sprite_animation_event_receiver_clear_markers(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_sprite_animation_event_receiver_add_marker(SparkGameComponent* component, uint32_t clipIndex, float normalizedTime, const char* eventName);

SPARK_SCRIPT_API void spark_sprite_animation_event_vfx_clear_bindings(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_sprite_animation_event_vfx_add_binding(SparkGameComponent* component, const char* eventName, const char* vfxAssetKey);
SPARK_SCRIPT_API void spark_sprite_animation_event_vfx_set_world_offset(SparkGameComponent* component, const SparkVector3* offset);
SPARK_SCRIPT_API void spark_sprite_animation_event_vfx_get_world_offset(const SparkGameComponent* component, SparkVector3* outWorldOffset);

SPARK_SCRIPT_API int spark_ambient_zone_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ambient_zone_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API int spark_ambient_zone_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ambient_zone_set_shape(SparkGameComponent* component, int s);
SPARK_SCRIPT_API void spark_ambient_zone_get_half_extents(const SparkGameComponent* component, SparkVector3* outHalfExtents);
SPARK_SCRIPT_API void spark_ambient_zone_set_half_extents(SparkGameComponent* component, const SparkVector3* e);
SPARK_SCRIPT_API float spark_ambient_zone_get_volume_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ambient_zone_set_volume_scale(SparkGameComponent* component, float v);
SPARK_SCRIPT_API float spark_ambient_zone_get_low_pass_amount(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ambient_zone_set_low_pass_amount(SparkGameComponent* component, float a);
SPARK_SCRIPT_API int32_t spark_ambient_zone_get_priority(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_ambient_zone_set_priority(SparkGameComponent* component, int32_t p);

SPARK_SCRIPT_API int32_t spark_audio_listener_get_priority(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_audio_listener_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_audio_listener_set_priority(SparkGameComponent* component, int32_t p);
SPARK_SCRIPT_API void spark_audio_listener_set_enabled(SparkGameComponent* component, int e);

SPARK_SCRIPT_API void spark_sound_cue_queue_preset(SparkGameComponent* component, int preset, float volume);
SPARK_SCRIPT_API void spark_sound_cue_queue_at_world_preset(SparkGameComponent* component, int preset, float volume, const SparkVector3* worldPosition, float spatialBlend, float minDistance, float maxDistance);

SPARK_SCRIPT_API float spark_camera_2d_get_half_extent_y(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_2d_get_clip_near_z(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_2d_get_clip_far_z(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_camera_2d_get_priority(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_camera_2d_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_camera_2d_set_clip_near_z(SparkGameComponent* component, float z);
SPARK_SCRIPT_API void spark_camera_2d_set_clip_far_z(SparkGameComponent* component, float z);
SPARK_SCRIPT_API void spark_camera_2d_world_position(const SparkGameComponent* component, SparkGameObject* owner, SparkVector3* outWorldPosition);

SPARK_SCRIPT_API int spark_camera_2d_rig_get_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_camera_2d_rig_get_target_offset(const SparkGameComponent* component, SparkVector3* outTargetOffset);
SPARK_SCRIPT_API float spark_camera_2d_rig_get_follow_smooth_rate(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_2d_rig_get_look_ahead_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_camera_2d_rig_get_use_bounds(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_camera_2d_rig_get_bounds_min(const SparkGameComponent* component, SparkVector2* outBoundsMin);
SPARK_SCRIPT_API void spark_camera_2d_rig_get_bounds_max(const SparkGameComponent* component, SparkVector2* outBoundsMax);
SPARK_SCRIPT_API int spark_camera_2d_rig_get_use_zoom_limits(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_2d_rig_get_zoom_min_half_extent_y(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_2d_rig_get_zoom_max_half_extent_y(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_camera_2d_rig_set_use_bounds(SparkGameComponent* component, int b);
SPARK_SCRIPT_API void spark_camera_2d_rig_set_bounds_min(SparkGameComponent* component, const SparkVector2* v);
SPARK_SCRIPT_API void spark_camera_2d_rig_set_bounds_max(SparkGameComponent* component, const SparkVector2* v);
SPARK_SCRIPT_API void spark_camera_2d_rig_set_use_zoom_limits(SparkGameComponent* component, int b);
SPARK_SCRIPT_API void spark_camera_2d_rig_set_zoom_min_half_extent_y(SparkGameComponent* component, float h);
SPARK_SCRIPT_API void spark_camera_2d_rig_set_zoom_max_half_extent_y(SparkGameComponent* component, float h);

SPARK_SCRIPT_API void spark_camera_bounds2_d_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_camera_bounds2_d_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_camera_bounds2_d_set_local_offset(SparkGameComponent* component, const SparkVector2* offset);
SPARK_SCRIPT_API void spark_camera_bounds2_d_get_local_offset(const SparkGameComponent* component, SparkVector2* outLocalOffset);
SPARK_SCRIPT_API void spark_camera_bounds2_d_set_half_extents(SparkGameComponent* component, const SparkVector2* value);
SPARK_SCRIPT_API void spark_camera_bounds2_d_get_half_extents(const SparkGameComponent* component, SparkVector2* outHalfExtents);
SPARK_SCRIPT_API void spark_camera_bounds2_d_set_priority(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_camera_bounds2_d_get_priority(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_camera_bounds2_d_is_contains_world_point(const SparkGameComponent* component, SparkGameObject* owner, float worldX, float worldY);

SPARK_SCRIPT_API int spark_camera_get_projection_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_get_fov_y_degrees(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_get_near_plane(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_get_far_plane(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_camera_get_ortho_half_height(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_camera_get_priority(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_camera_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_camera_set_projection_mode(SparkGameComponent* component, int mode);
SPARK_SCRIPT_API void spark_camera_set_fov_y_degrees(SparkGameComponent* component, float degrees);
SPARK_SCRIPT_API void spark_camera_set_near_plane(SparkGameComponent* component, float z);
SPARK_SCRIPT_API void spark_camera_set_far_plane(SparkGameComponent* component, float z);
SPARK_SCRIPT_API void spark_camera_set_ortho_half_height(SparkGameComponent* component, float h);
SPARK_SCRIPT_API void spark_camera_set_priority(SparkGameComponent* component, int32_t p);
SPARK_SCRIPT_API void spark_camera_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API void spark_camera_world_position(const SparkGameComponent* component, SparkGameObject* owner, SparkVector3* outWorldPosition);

SPARK_SCRIPT_API void spark_camera_follow3_d_get_target_offset(const SparkGameComponent* component, SparkVector3* outTargetOffset);
SPARK_SCRIPT_API float spark_camera_follow3_d_get_follow_smooth_rate(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_camera_follow3_d_get_look_at_target(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_camera_follow3_d_set_target(SparkGameComponent* component, SparkGameObject* o);
SPARK_SCRIPT_API void spark_camera_follow3_d_set_target_offset(SparkGameComponent* component, const SparkVector3* o);
SPARK_SCRIPT_API void spark_camera_follow3_d_set_follow_smooth_rate(SparkGameComponent* component, float r);
SPARK_SCRIPT_API void spark_camera_follow3_d_set_look_at_target(SparkGameComponent* component, int v);

SPARK_SCRIPT_API void spark_screen_shake_add_impulse(SparkGameComponent* component, const SparkVector2* amplitude, float durationSeconds, float frequencyHz);
SPARK_SCRIPT_API void spark_screen_shake_add_trauma(SparkGameComponent* component, float amount);
SPARK_SCRIPT_API void spark_screen_shake_get_offset(const SparkGameComponent* component, SparkVector2* outOffset);
SPARK_SCRIPT_API void spark_screen_shake_clear(SparkGameComponent* component);

SPARK_SCRIPT_API void spark_spring_arm3_d_get_socket_offset(const SparkGameComponent* component, SparkVector3* outSocketOffset);
SPARK_SCRIPT_API float spark_spring_arm3_d_get_arm_length(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_spring_arm3_d_get_yaw_radians(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_spring_arm3_d_get_pitch_radians(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_spring_arm3_d_get_probe_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_spring_arm3_d_get_min_arm_length(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_spring_arm3_d_set_pivot_target(SparkGameComponent* component, SparkGameObject* o);
SPARK_SCRIPT_API void spark_spring_arm3_d_set_socket_offset(SparkGameComponent* component, const SparkVector3* o);
SPARK_SCRIPT_API void spark_spring_arm3_d_set_arm_length(SparkGameComponent* component, float l);
SPARK_SCRIPT_API void spark_spring_arm3_d_set_yaw_radians(SparkGameComponent* component, float y);
SPARK_SCRIPT_API void spark_spring_arm3_d_set_pitch_radians(SparkGameComponent* component, float p);
SPARK_SCRIPT_API void spark_spring_arm3_d_set_probe_radius(SparkGameComponent* component, float r);
SPARK_SCRIPT_API void spark_spring_arm3_d_set_min_arm_length(SparkGameComponent* component, float l);

SPARK_SCRIPT_API int spark_foliage_instanced_is_enabled(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_grass_field_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_grass_field_get_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grass_field_set_terrain_object(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_grass_field_set_view_target_object(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_grass_field_set_streaming_view_world(SparkGameComponent* component, const SparkVector3* worldPosition);
SPARK_SCRIPT_API void spark_grass_field_prepare_for_render(SparkGameComponent* component, SparkGameObject* owner, const SparkVector3* viewWorldPosition, uint32_t sceneMaxGrassInstancesPerFrame);
SPARK_SCRIPT_API void spark_grass_field_set_neighborhood_ring_radius(SparkGameComponent* component, int radiusChunks);
SPARK_SCRIPT_API int spark_grass_field_get_neighborhood_ring_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grass_field_set_alpha_cutoff(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_grass_field_get_alpha_cutoff(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grass_field_set_wind_bend_scale(SparkGameComponent* component, float scale);
SPARK_SCRIPT_API float spark_grass_field_get_wind_bend_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_grass_field_bounds_set_half_extents(SparkGameComponent* component, float halfX, float halfZ);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_chunk_size_meters(SparkGameComponent* component, float meters);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_density_per_square_meter(SparkGameComponent* component, float density);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_max_view_distance_meters(SparkGameComponent* component, float meters);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_max_visible_instances(SparkGameComponent* component, uint32_t count);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_max_cached_instances_per_chunk(SparkGameComponent* component, uint32_t count);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_max_slope_degrees(SparkGameComponent* component, float degrees);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_placement_radius_meters(SparkGameComponent* component, float meters);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_distance_fade_outer_fraction(SparkGameComponent* component, float fraction);
SPARK_SCRIPT_API void spark_grass_field_scatter_set_albedo_tint(SparkGameComponent* component, const SparkVector3* rgb);

SPARK_SCRIPT_API void spark_wind_environment_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_wind_environment_get_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_wind_environment_set_direction(SparkGameComponent* component, const SparkVector3* directionWorld);
SPARK_SCRIPT_API void spark_wind_environment_get_direction(const SparkGameComponent* component, SparkVector3* outDirectionWorld);
SPARK_SCRIPT_API void spark_wind_environment_set_base_speed(SparkGameComponent* component, float metersPerSecond);
SPARK_SCRIPT_API float spark_wind_environment_get_base_speed(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_wind_environment_set_gust_amplitude(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_wind_environment_get_gust_amplitude(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_wind_environment_set_gust_frequency(SparkGameComponent* component, float hertz);
SPARK_SCRIPT_API float spark_wind_environment_get_gust_frequency(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_wind_environment_set_turbulence(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_wind_environment_get_turbulence(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_damage_zone2_d_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_damage_zone2_d_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_damage_zone2_d_set_shape(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_damage_zone2_d_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_damage_zone2_d_set_local_offset(SparkGameComponent* component, const SparkVector2* offset);
SPARK_SCRIPT_API void spark_damage_zone2_d_get_local_offset(const SparkGameComponent* component, SparkVector2* outLocalOffset);
SPARK_SCRIPT_API void spark_damage_zone2_d_set_radius(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_damage_zone2_d_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_damage_zone2_d_set_half_extents(SparkGameComponent* component, const SparkVector2* value);
SPARK_SCRIPT_API void spark_damage_zone2_d_get_half_extents(const SparkGameComponent* component, SparkVector2* outHalfExtents);
SPARK_SCRIPT_API void spark_damage_zone2_d_set_damage_per_second(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_damage_zone2_d_get_damage_per_second(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_damage_zone2_d_set_category_bits(SparkGameComponent* component, int bits);
SPARK_SCRIPT_API void spark_damage_zone2_d_set_mask_bits(SparkGameComponent* component, int bits);
SPARK_SCRIPT_API void spark_damage_zone2_d_set_instigator(SparkGameComponent* component, SparkGameObject* object);

SPARK_SCRIPT_API float spark_damageable_get_damage_multiplier(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_damageable_is_invulnerable(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_damageable_set_damage_multiplier(SparkGameComponent* component, float m);
SPARK_SCRIPT_API void spark_damageable_set_invulnerable(SparkGameComponent* component, int v);
SPARK_SCRIPT_API float spark_damageable_get_apply_damage(SparkGameComponent* component, float amount, SparkGameObject* instigator);

SPARK_SCRIPT_API void spark_fog_of_war2_d_set_vision_radius_world(SparkGameComponent* component, float radius);
SPARK_SCRIPT_API float spark_fog_of_war2_d_get_vision_radius_world(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_fog_of_war2_d_set_reveal_target(SparkGameComponent* component, SparkGameObject* target);
SPARK_SCRIPT_API void spark_fog_of_war2_d_rebuild_mask_texture(SparkGameComponent* component);

SPARK_SCRIPT_API void spark_game_flow_trigger_set_source(SparkGameComponent* component, SparkGameFlowTriggerSource value);
SPARK_SCRIPT_API void spark_game_flow_trigger_set_target_state(SparkGameComponent* component, SparkGameFlowState state);
SPARK_SCRIPT_API void spark_game_flow_trigger_set_instigator_name_filter(SparkGameComponent* component, const char* filter);
SPARK_SCRIPT_API void spark_game_flow_trigger_set_state_owner(SparkGameComponent* component, SparkGameObject* owner);

SPARK_SCRIPT_API SparkGameFlowState spark_game_state_get_state(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_game_state_request_state(SparkGameComponent* component, SparkGameFlowState nextState);
SPARK_SCRIPT_API void spark_game_state_push_state(SparkGameComponent* component, SparkGameFlowState nextState);
SPARK_SCRIPT_API int spark_game_state_pop_state(SparkGameComponent* component);

SPARK_SCRIPT_API float spark_health_get_maximum(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_health_get_current(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_health_is_alive(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_health_set_maximum(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_health_set_current(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_health_reset_to_full(SparkGameComponent* component);
SPARK_SCRIPT_API float spark_health_get_apply_damage(SparkGameComponent* component, float amount, SparkGameObject* instigator);

SPARK_SCRIPT_API void spark_interactable_set_prompt_text(SparkGameComponent* component, const char* text);
SPARK_SCRIPT_API void spark_interactable_set_interaction_radius(SparkGameComponent* component, float radius);
SPARK_SCRIPT_API float spark_interactable_get_interaction_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_interactable_set_required_instigator_tag(SparkGameComponent* component, const char* tag);
SPARK_SCRIPT_API void spark_interactable_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_interactable_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_interactable_is_instigator_in_range(const SparkGameComponent* component, SparkGameObject* instigator);
SPARK_SCRIPT_API int spark_interactable_is_can_interact(const SparkGameComponent* component, SparkGameObject* instigator);

SPARK_SCRIPT_API void spark_pickup_set_item_id(SparkGameComponent* component, const char* id);
SPARK_SCRIPT_API void spark_pickup_set_quantity(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_pickup_get_quantity(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_pickup_set_auto_collect_on_trigger_enter(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_pickup_get_auto_collect_on_trigger_enter(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_pickup_set_destroy_owner_on_collect(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_pickup_get_destroy_owner_on_collect(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_pickup_is_collected(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_input_action_map_clear(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_input_action_map_bind_button(SparkGameComponent* component, const char* actionName, int primaryKey, int secondaryKey);
SPARK_SCRIPT_API void spark_input_action_map_bind_axis1d(SparkGameComponent* component, const char* actionName, int negativeKey, int positiveKey, int secondaryNegativeKey, int secondaryPositiveKey);

SPARK_SCRIPT_API void spark_player_input_set_action_map(SparkGameComponent* component, SparkGameComponent* mapIn);
SPARK_SCRIPT_API int spark_player_input_is_action_pressed(const SparkGameComponent* component, const char* actionName);
SPARK_SCRIPT_API int spark_player_input_was_action_pressed_this_frame(const SparkGameComponent* component, const char* actionName);
SPARK_SCRIPT_API float spark_player_input_get_action_axis1d(const SparkGameComponent* component, const char* actionName);

SPARK_SCRIPT_API void spark_directional_light_get_color(const SparkGameComponent* component, SparkVector3* outColor);
SPARK_SCRIPT_API float spark_directional_light_get_intensity(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_directional_light_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_directional_light_is_casts_shadow(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_directional_light_set_color(SparkGameComponent* component, const SparkVector3* c);
SPARK_SCRIPT_API void spark_directional_light_set_intensity(SparkGameComponent* component, float v);
SPARK_SCRIPT_API void spark_directional_light_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API void spark_directional_light_set_casts_shadow(SparkGameComponent* component, int c);

SPARK_SCRIPT_API void spark_point_light2_d_get_local_offset(const SparkGameComponent* component, SparkVector2* outLocalOffset);
SPARK_SCRIPT_API float spark_point_light2_d_get_world_z(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_point_light2_d_get_color(const SparkGameComponent* component, SparkVector3* outColor);
SPARK_SCRIPT_API float spark_point_light2_d_get_intensity(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_point_light2_d_get_effective_intensity(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_point_light2_d_get_range(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_point_light2_d_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_point_light2_d_set_local_offset(SparkGameComponent* component, const SparkVector2* offset);
SPARK_SCRIPT_API void spark_point_light2_d_set_world_z(SparkGameComponent* component, float z);
SPARK_SCRIPT_API void spark_point_light2_d_set_color(SparkGameComponent* component, const SparkVector3* c);
SPARK_SCRIPT_API void spark_point_light2_d_set_intensity(SparkGameComponent* component, float v);
SPARK_SCRIPT_API void spark_point_light2_d_set_range(SparkGameComponent* component, float r);
SPARK_SCRIPT_API void spark_point_light2_d_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API void spark_point_light2_d_set_flicker(SparkGameComponent* component, int on, float amount, float frequencyHz);
SPARK_SCRIPT_API int spark_point_light2_d_get_flicker_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_point_light2_d_get_flicker_amount(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_point_light2_d_get_flicker_hz(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_box_collider_2d_get_half_extents(const SparkGameComponent* component, SparkVector2* outHalfExtents);
SPARK_SCRIPT_API void spark_box_collider_2d_get_offset(const SparkGameComponent* component, SparkVector2* outOffset);
SPARK_SCRIPT_API void spark_box_collider_2d_set_offset(SparkGameComponent* component, const SparkVector2* o);
SPARK_SCRIPT_API int spark_box_collider_2d_get_is_trigger(const SparkGameComponent* component);

SPARK_SCRIPT_API float spark_character_controller2_d_get_move_speed(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_set_move_speed(SparkGameComponent* component, float speed);
SPARK_SCRIPT_API float spark_character_controller2_d_get_jump_speed(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_set_jump_speed(SparkGameComponent* component, float speed);
SPARK_SCRIPT_API float spark_character_controller2_d_get_coyote_time_seconds(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_set_coyote_time_seconds(SparkGameComponent* component, float seconds);
SPARK_SCRIPT_API float spark_character_controller2_d_get_jump_buffer_seconds(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_set_jump_buffer_seconds(SparkGameComponent* component, float seconds);
SPARK_SCRIPT_API float spark_character_controller2_d_get_snap_to_ground_distance(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_character_controller2_d_get_slope_limit_degrees(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_character_controller2_d_get_skin_width(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_set_skin_width(SparkGameComponent* component, float width);
SPARK_SCRIPT_API void spark_character_controller2_d_set_move_input_x(SparkGameComponent* component, float normalized);
SPARK_SCRIPT_API float spark_character_controller2_d_get_move_input_x(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_set_move_input_y(SparkGameComponent* component, float normalized);
SPARK_SCRIPT_API float spark_character_controller2_d_get_move_input_y(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_set_motor_mode(SparkGameComponent* component, int mode);
SPARK_SCRIPT_API int spark_character_controller2_d_get_motor_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_request_jump(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller2_d_set_drop_through_one_way(SparkGameComponent* component, int drop);
SPARK_SCRIPT_API int spark_character_controller2_d_get_drop_through_one_way(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_character_controller2_d_is_grounded(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_character_controller2_d_is_was_grounded_last_frame(const SparkGameComponent* component);

SPARK_SCRIPT_API float spark_circle_collider_2d_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_circle_collider_2d_get_offset(const SparkGameComponent* component, SparkVector2* outOffset);
SPARK_SCRIPT_API void spark_circle_collider_2d_set_offset(SparkGameComponent* component, const SparkVector2* o);
SPARK_SCRIPT_API int spark_circle_collider_2d_get_is_trigger(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_distance_joint2_d_set_connected_body(SparkGameComponent* component, SparkGameObject* o);
SPARK_SCRIPT_API float spark_distance_joint2_d_get_rest_length(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_distance_joint2_d_set_rest_length(SparkGameComponent* component, float r);
SPARK_SCRIPT_API void spark_distance_joint2_d_get_local_anchor_a(const SparkGameComponent* component, SparkVector2* outLocalAnchorA);
SPARK_SCRIPT_API void spark_distance_joint2_d_set_local_anchor_a(SparkGameComponent* component, const SparkVector2* a);
SPARK_SCRIPT_API void spark_distance_joint2_d_get_local_anchor_b(const SparkGameComponent* component, SparkVector2* outLocalAnchorB);
SPARK_SCRIPT_API void spark_distance_joint2_d_set_local_anchor_b(SparkGameComponent* component, const SparkVector2* b);
SPARK_SCRIPT_API float spark_distance_joint2_d_get_stiffness(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_distance_joint2_d_set_stiffness(SparkGameComponent* component, float s);

SPARK_SCRIPT_API void spark_hinge_joint2_d_set_connected_body(SparkGameComponent* component, SparkGameObject* o);
SPARK_SCRIPT_API void spark_hinge_joint2_d_get_local_anchor_a(const SparkGameComponent* component, SparkVector2* outLocalAnchorA);
SPARK_SCRIPT_API void spark_hinge_joint2_d_set_local_anchor_a(SparkGameComponent* component, const SparkVector2* a);
SPARK_SCRIPT_API void spark_hinge_joint2_d_get_local_anchor_b(const SparkGameComponent* component, SparkVector2* outLocalAnchorB);
SPARK_SCRIPT_API void spark_hinge_joint2_d_set_local_anchor_b(SparkGameComponent* component, const SparkVector2* b);
SPARK_SCRIPT_API float spark_hinge_joint2_d_get_stiffness(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_hinge_joint2_d_set_stiffness(SparkGameComponent* component, float s);

SPARK_SCRIPT_API void spark_hurtbox2_d_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_hurtbox2_d_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_hurtbox2_d_set_shape(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_hurtbox2_d_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_hurtbox2_d_set_local_offset(SparkGameComponent* component, const SparkVector2* offset);
SPARK_SCRIPT_API void spark_hurtbox2_d_get_local_offset(const SparkGameComponent* component, SparkVector2* outLocalOffset);
SPARK_SCRIPT_API void spark_hurtbox2_d_set_radius(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_hurtbox2_d_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_hurtbox2_d_set_half_extents(SparkGameComponent* component, const SparkVector2* value);
SPARK_SCRIPT_API void spark_hurtbox2_d_get_half_extents(const SparkGameComponent* component, SparkVector2* outHalfExtents);
SPARK_SCRIPT_API void spark_hurtbox2_d_set_category_bits(SparkGameComponent* component, int bits);
SPARK_SCRIPT_API void spark_hurtbox2_d_set_mask_bits(SparkGameComponent* component, int bits);
SPARK_SCRIPT_API void spark_hurtbox2_d_set_invulnerability_seconds(SparkGameComponent* component, float seconds);
SPARK_SCRIPT_API float spark_hurtbox2_d_get_invulnerability_seconds(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_hurtbox2_d_is_invulnerable(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_hurtbox2_d_notify_damage_received(SparkGameComponent* component);

SPARK_SCRIPT_API int spark_one_way_platform_2d_is_one_way_platform(const SparkGameComponent* component);

SPARK_SCRIPT_API float spark_physics_material2_d_get_dynamic_friction(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_physics_material2_d_set_dynamic_friction(SparkGameComponent* component, float v);
SPARK_SCRIPT_API float spark_physics_material2_d_get_restitution(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_physics_material2_d_set_restitution(SparkGameComponent* component, float v);

SPARK_SCRIPT_API void spark_polygon_collider2_d_clear_vertices(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_polygon_collider2_d_set_category_bits(SparkGameComponent* component, int bits);
SPARK_SCRIPT_API void spark_polygon_collider2_d_set_mask_bits(SparkGameComponent* component, int bits);
SPARK_SCRIPT_API int spark_polygon_collider2_d_get_is_trigger(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_polygon_collider2_d_set_is_trigger(SparkGameComponent* component, int value);

SPARK_SCRIPT_API void spark_projectile2_d_set_active(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_projectile2_d_is_active(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_projectile2_d_deactivate(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_projectile2_d_set_shape(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_projectile2_d_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_projectile2_d_set_radius(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_projectile2_d_set_half_extents(SparkGameComponent* component, const SparkVector2* value);
SPARK_SCRIPT_API void spark_projectile2_d_set_damage(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_projectile2_d_get_damage(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_projectile2_d_set_lifetime_seconds(SparkGameComponent* component, float seconds);
SPARK_SCRIPT_API float spark_projectile2_d_get_lifetime_seconds(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_projectile2_d_set_instigator(SparkGameComponent* component, SparkGameObject* object);
SPARK_SCRIPT_API void spark_projectile2_d_set_block_on_solid_hit(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_projectile2_d_get_block_on_solid_hit(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_projectile2_d_set_destroy_owner_on_deactivate(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_projectile2_d_get_destroy_owner_on_deactivate(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_projectile2_d_set_deactivate_on_first_hit(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_projectile2_d_get_deactivate_on_first_hit(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_projectile2_d_get_velocity(const SparkGameComponent* component, SparkVector2* outVelocity);
SPARK_SCRIPT_API void spark_projectile2_d_set_velocity(SparkGameComponent* component, const SparkVector2* value);

SPARK_SCRIPT_API int spark_rigidbody_2d_get_body_type(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_rigidbody_2d_set_body_type(SparkGameComponent* component, int t);
SPARK_SCRIPT_API float spark_rigidbody_2d_get_gravity_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_rigidbody_2d_set_gravity_scale(SparkGameComponent* component, float g);
SPARK_SCRIPT_API void spark_rigidbody_2d_set_velocity_x(SparkGameComponent* component, float x);
SPARK_SCRIPT_API void spark_rigidbody_2d_set_velocity_y(SparkGameComponent* component, float y);
SPARK_SCRIPT_API void spark_rigidbody_2d_set_grounded(SparkGameComponent* component, int g);

SPARK_SCRIPT_API void spark_tilemap_collider2_d_set_category_bits(SparkGameComponent* component, int bits);
SPARK_SCRIPT_API void spark_tilemap_collider2_d_set_mask_bits(SparkGameComponent* component, int bits);
SPARK_SCRIPT_API int spark_tilemap_collider2_d_get_is_trigger(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_collider2_d_set_is_trigger(SparkGameComponent* component, int value);

SPARK_SCRIPT_API int spark_trigger_volume2_d_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_trigger_volume2_d_set_shape(SparkGameComponent* component, int value);
SPARK_SCRIPT_API void spark_trigger_volume2_d_get_half_extents(const SparkGameComponent* component, SparkVector2* outHalfExtents);
SPARK_SCRIPT_API void spark_trigger_volume2_d_set_half_extents(SparkGameComponent* component, const SparkVector2* value);
SPARK_SCRIPT_API float spark_trigger_volume2_d_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_trigger_volume2_d_set_radius(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_trigger_volume2_d_get_offset(const SparkGameComponent* component, SparkVector2* outOffset);
SPARK_SCRIPT_API void spark_trigger_volume2_d_set_offset(SparkGameComponent* component, const SparkVector2* value);
SPARK_SCRIPT_API void spark_trigger_volume2_d_set_filter_tag(SparkGameComponent* component, const char* tag);
SPARK_SCRIPT_API int spark_trigger_volume2_d_is_overlapping(const SparkGameComponent* component, SparkGameObject* other);

SPARK_SCRIPT_API void spark_box_collider3_d_get_half_extents(const SparkGameComponent* component, SparkVector3* outHalfExtents);
SPARK_SCRIPT_API void spark_box_collider3_d_get_offset(const SparkGameComponent* component, SparkVector3* outOffset);
SPARK_SCRIPT_API void spark_box_collider3_d_set_half_extents(SparkGameComponent* component, const SparkVector3* h);
SPARK_SCRIPT_API void spark_box_collider3_d_set_offset(SparkGameComponent* component, const SparkVector3* o);

SPARK_SCRIPT_API float spark_capsule_collider3_d_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_capsule_collider3_d_set_radius(SparkGameComponent* component, float r);
SPARK_SCRIPT_API float spark_capsule_collider3_d_get_height(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_capsule_collider3_d_set_height(SparkGameComponent* component, float h);
SPARK_SCRIPT_API int spark_capsule_collider3_d_get_direction(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_capsule_collider3_d_set_direction(SparkGameComponent* component, int axis);
SPARK_SCRIPT_API void spark_capsule_collider3_d_get_offset(const SparkGameComponent* component, SparkVector3* outOffset);
SPARK_SCRIPT_API void spark_capsule_collider3_d_set_offset(SparkGameComponent* component, const SparkVector3* o);

SPARK_SCRIPT_API float spark_character_controller3_d_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller3_d_set_radius(SparkGameComponent* component, float r);
SPARK_SCRIPT_API void spark_character_controller3_d_get_center_offset(const SparkGameComponent* component, SparkVector3* outCenterOffset);
SPARK_SCRIPT_API void spark_character_controller3_d_set_center_offset(SparkGameComponent* component, const SparkVector3* o);
SPARK_SCRIPT_API float spark_character_controller3_d_get_slope_limit_degrees(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_character_controller3_d_get_step_offset(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller3_d_set_step_offset(SparkGameComponent* component, float meters);
SPARK_SCRIPT_API float spark_character_controller3_d_get_skin_width(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller3_d_set_skin_width(SparkGameComponent* component, float w);
SPARK_SCRIPT_API float spark_character_controller3_d_get_gravity_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_character_controller3_d_set_gravity_scale(SparkGameComponent* component, float g);
SPARK_SCRIPT_API void spark_character_controller3_d_get_move_input(const SparkGameComponent* component, SparkVector3* outMoveInput);
SPARK_SCRIPT_API void spark_character_controller3_d_get_velocity(const SparkGameComponent* component, SparkVector3* outVelocity);
SPARK_SCRIPT_API int spark_character_controller3_d_is_grounded(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_distance_joint3_d_set_connected_body(SparkGameComponent* component, SparkGameObject* o);
SPARK_SCRIPT_API float spark_distance_joint3_d_get_rest_length(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_distance_joint3_d_set_rest_length(SparkGameComponent* component, float r);
SPARK_SCRIPT_API float spark_distance_joint3_d_get_stiffness(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_distance_joint3_d_set_stiffness(SparkGameComponent* component, float s);

SPARK_SCRIPT_API void spark_hinge_joint3_d_set_connected_body(SparkGameComponent* component, SparkGameObject* o);
SPARK_SCRIPT_API void spark_hinge_joint3_d_get_local_anchor_a(const SparkGameComponent* component, SparkVector3* outLocalAnchorA);
SPARK_SCRIPT_API void spark_hinge_joint3_d_set_local_anchor_a(SparkGameComponent* component, const SparkVector3* a);
SPARK_SCRIPT_API void spark_hinge_joint3_d_get_local_anchor_b(const SparkGameComponent* component, SparkVector3* outLocalAnchorB);
SPARK_SCRIPT_API void spark_hinge_joint3_d_set_local_anchor_b(SparkGameComponent* component, const SparkVector3* b);
SPARK_SCRIPT_API float spark_hinge_joint3_d_get_stiffness(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_hinge_joint3_d_set_stiffness(SparkGameComponent* component, float s);

SPARK_SCRIPT_API void spark_mesh_collider3_d_get_local_offset(const SparkGameComponent* component, SparkVector3* outLocalOffset);
SPARK_SCRIPT_API void spark_mesh_collider3_d_set_local_offset(SparkGameComponent* component, const SparkVector3* o);
SPARK_SCRIPT_API int spark_mesh_collider3_d_is_trigger(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_mesh_collider3_d_set_is_trigger(SparkGameComponent* component, int t);

SPARK_SCRIPT_API float spark_physics_material3_d_get_static_friction(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_physics_material3_d_set_static_friction(SparkGameComponent* component, float v);
SPARK_SCRIPT_API float spark_physics_material3_d_get_dynamic_friction(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_physics_material3_d_set_dynamic_friction(SparkGameComponent* component, float v);
SPARK_SCRIPT_API float spark_physics_material3_d_get_restitution(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_physics_material3_d_set_restitution(SparkGameComponent* component, float v);

SPARK_SCRIPT_API float spark_rigidbody_3d_get_linear_damping(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_rigidbody_3d_get_angular_damping(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_rigidbody_3d_get_inverse_inertia_tensor_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_rigidbody_3d_set_inverse_inertia_tensor_scale(SparkGameComponent* component, float invI);
SPARK_SCRIPT_API float spark_rigidbody_3d_get_inverse_mass(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_rigidbody_3d_get_body_type(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_rigidbody_3d_set_body_type(SparkGameComponent* component, int t);
SPARK_SCRIPT_API float spark_rigidbody_3d_get_gravity_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_rigidbody_3d_set_gravity_scale(SparkGameComponent* component, float g);
SPARK_SCRIPT_API float spark_rigidbody_3d_get_restitution(const SparkGameComponent* component);

SPARK_SCRIPT_API float spark_sphere_collider3_d_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_sphere_collider3_d_get_offset(const SparkGameComponent* component, SparkVector3* outOffset);
SPARK_SCRIPT_API void spark_sphere_collider3_d_set_radius(SparkGameComponent* component, float r);
SPARK_SCRIPT_API void spark_sphere_collider3_d_set_offset(SparkGameComponent* component, const SparkVector3* o);

SPARK_SCRIPT_API void spark_spring_joint3_d_set_connected_body(SparkGameComponent* component, SparkGameObject* o);
SPARK_SCRIPT_API float spark_spring_joint3_d_get_rest_length(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_spring_joint3_d_set_rest_length(SparkGameComponent* component, float r);
SPARK_SCRIPT_API float spark_spring_joint3_d_get_spring_stiffness(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_spring_joint3_d_set_spring_stiffness(SparkGameComponent* component, float k);
SPARK_SCRIPT_API float spark_spring_joint3_d_get_damping(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_spring_joint3_d_set_damping(SparkGameComponent* component, float d);

SPARK_SCRIPT_API int spark_trigger_volume3_d_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_trigger_volume3_d_set_shape(SparkGameComponent* component, int value);
SPARK_SCRIPT_API void spark_trigger_volume3_d_get_half_extents(const SparkGameComponent* component, SparkVector3* outHalfExtents);
SPARK_SCRIPT_API void spark_trigger_volume3_d_set_half_extents(SparkGameComponent* component, const SparkVector3* value);
SPARK_SCRIPT_API float spark_trigger_volume3_d_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_trigger_volume3_d_set_radius(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_trigger_volume3_d_get_height(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_trigger_volume3_d_set_height(SparkGameComponent* component, float value);
SPARK_SCRIPT_API int spark_trigger_volume3_d_get_capsule_direction(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_trigger_volume3_d_set_capsule_direction(SparkGameComponent* component, int axis);
SPARK_SCRIPT_API void spark_trigger_volume3_d_get_offset(const SparkGameComponent* component, SparkVector3* outOffset);
SPARK_SCRIPT_API void spark_trigger_volume3_d_set_offset(SparkGameComponent* component, const SparkVector3* value);
SPARK_SCRIPT_API void spark_trigger_volume3_d_set_filter_tag(SparkGameComponent* component, const char* tag);
SPARK_SCRIPT_API int spark_trigger_volume3_d_is_overlapping(const SparkGameComponent* component, SparkGameObject* other);

SPARK_SCRIPT_API float spark_collision_get_radius(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_collision_get_local_center(const SparkGameComponent* component, SparkVector3* outLocalCenter);
SPARK_SCRIPT_API void spark_collision_get_world_center(const SparkGameComponent* component, SparkVector3* outWorldCenter);
SPARK_SCRIPT_API void spark_collision_set_radius(SparkGameComponent* component, float r);
SPARK_SCRIPT_API void spark_collision_set_local_center(SparkGameComponent* component, const SparkVector3* c);

SPARK_SCRIPT_API int spark_billboard_get_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_billboard_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_billboard_set_mode(SparkGameComponent* component, int m);
SPARK_SCRIPT_API void spark_billboard_set_enabled(SparkGameComponent* component, int e);

SPARK_SCRIPT_API int spark_blend_mode_get_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_blend_mode_set_mode(SparkGameComponent* component, int m);

SPARK_SCRIPT_API void spark_decal_projector_get_size(const SparkGameComponent* component, SparkVector3* outSize);
SPARK_SCRIPT_API float spark_decal_projector_get_opacity(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_decal_projector_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_decal_projector_set_size(SparkGameComponent* component, const SparkVector3* s);
SPARK_SCRIPT_API void spark_decal_projector_set_opacity(SparkGameComponent* component, float o);
SPARK_SCRIPT_API void spark_decal_projector_set_enabled(SparkGameComponent* component, int e);

SPARK_SCRIPT_API int spark_fog_volume_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_fog_volume_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API int spark_fog_volume_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_fog_volume_set_shape(SparkGameComponent* component, int s);
SPARK_SCRIPT_API void spark_fog_volume_get_half_extents(const SparkGameComponent* component, SparkVector3* outHalfExtents);
SPARK_SCRIPT_API void spark_fog_volume_set_half_extents(SparkGameComponent* component, const SparkVector3* e);
SPARK_SCRIPT_API void spark_fog_volume_get_fog_color(const SparkGameComponent* component, SparkVector3* outFogColor);
SPARK_SCRIPT_API void spark_fog_volume_set_fog_color(SparkGameComponent* component, const SparkVector3* c);
SPARK_SCRIPT_API float spark_fog_volume_get_fog_density(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_fog_volume_set_fog_density(SparkGameComponent* component, float d);
SPARK_SCRIPT_API float spark_fog_volume_get_fog_start(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_fog_volume_set_fog_start(SparkGameComponent* component, float s);
SPARK_SCRIPT_API float spark_fog_volume_get_fog_end(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_fog_volume_set_fog_end(SparkGameComponent* component, float e);
SPARK_SCRIPT_API int32_t spark_fog_volume_get_priority(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_fog_volume_set_priority(SparkGameComponent* component, int32_t p);

SPARK_SCRIPT_API int32_t spark_gltf_instance_node_get_node_index(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_gltf_instance_node_set_node_index(SparkGameComponent* component, uint32_t index);

SPARK_SCRIPT_API void spark_gltf_scene_source_set_gltf_asset_rel(SparkGameComponent* component, const char* path);

SPARK_SCRIPT_API void spark_multi_material_clear(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_multi_material_resize_slots(SparkGameComponent* component, int count);
SPARK_SCRIPT_API int spark_multi_material_is_slot_has_material_asset(const SparkGameComponent* component, int index);
SPARK_SCRIPT_API int32_t spark_multi_material_get_active_variant_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_multi_material_has_s_material_variants(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_multi_material_set_active_variant_index(SparkGameComponent* component, uint32_t index);
SPARK_SCRIPT_API void spark_multi_material_cycle_active_variant(SparkGameComponent* component);

SPARK_SCRIPT_API void spark_parallax_set_camera_reference(SparkGameComponent* component, SparkGameObject* camera);
SPARK_SCRIPT_API void spark_parallax_set_anchor_world(SparkGameComponent* component, const SparkVector3* anchor);
SPARK_SCRIPT_API void spark_parallax_get_anchor_world(const SparkGameComponent* component, SparkVector3* outAnchor);
SPARK_SCRIPT_API void spark_parallax_set_rest_offset(SparkGameComponent* component, const SparkVector3* offset);
SPARK_SCRIPT_API void spark_parallax_get_rest_offset(const SparkGameComponent* component, SparkVector3* outRestOffset);
SPARK_SCRIPT_API void spark_parallax_set_factor_x(SparkGameComponent* component, float factor);
SPARK_SCRIPT_API void spark_parallax_set_factor_y(SparkGameComponent* component, float factor);
SPARK_SCRIPT_API float spark_parallax_get_factor_x(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_parallax_get_factor_y(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_parallax_set_axis_mode(SparkGameComponent* component, SparkParallaxAxisMode mode);
SPARK_SCRIPT_API SparkParallaxAxisMode spark_parallax_get_axis_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_parallax_set_drift(SparkGameComponent* component, SparkParallaxDriftMode mode, float amplitude, float frequencyHz, float phase);
SPARK_SCRIPT_API void spark_parallax_set_drift_mode(SparkGameComponent* component, SparkParallaxDriftMode mode);
SPARK_SCRIPT_API void spark_parallax_set_drift_amplitude(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_parallax_set_drift_frequency_hz(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_parallax_set_drift_phase(SparkGameComponent* component, float value);

SPARK_SCRIPT_API int spark_post_process_volume_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_post_process_volume_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API int spark_post_process_volume_get_shape(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_post_process_volume_set_shape(SparkGameComponent* component, int s);
SPARK_SCRIPT_API void spark_post_process_volume_get_half_extents(const SparkGameComponent* component, SparkVector3* outHalfExtents);
SPARK_SCRIPT_API void spark_post_process_volume_set_half_extents(SparkGameComponent* component, const SparkVector3* e);
SPARK_SCRIPT_API int32_t spark_post_process_volume_get_priority(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_post_process_volume_set_priority(SparkGameComponent* component, int32_t p);
SPARK_SCRIPT_API int spark_post_process_volume_has_s_ssao_override(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_post_process_volume_get_ssao_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_post_process_volume_has_s_exposure_override(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_post_process_volume_get_exposure(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_post_process_volume_has_s_ambient_scale_override(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_post_process_volume_get_ambient_scale(const SparkGameComponent* component);

SPARK_SCRIPT_API void spark_scene2_d_composite_view_set_feature(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_scene2_d_composite_view_get_feature(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_scene2_d_composite_view_set_enabled(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_scene2_d_composite_view_is_enabled(const SparkGameComponent* component);

SPARK_SCRIPT_API int spark_skinned_mesh_is_mesh_loaded(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_skinned_mesh_is_skeleton_loaded(const SparkGameComponent* component);

SPARK_SCRIPT_API int spark_sprite_lighting2_d_get_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_sprite_lighting2_d_set_mode(SparkGameComponent* component, int m);
SPARK_SCRIPT_API void spark_sprite_lighting2_d_set_sync_normal_uv_with_sprite(SparkGameComponent* component, int sync);
SPARK_SCRIPT_API int spark_sprite_lighting2_d_get_sync_normal_uv_with_sprite(const SparkGameComponent* component);

SPARK_SCRIPT_API int32_t spark_terrain_get_subdiv_x(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_terrain_get_subdiv_z(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_terrain_get_half_extent_x(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_terrain_get_half_extent_z(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_terrain_get_height_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_terrain_get_noise_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_terrain_get_octaves(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_terrain_get_persistence(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_terrain_get_lacunarity(const SparkGameComponent* component);
SPARK_SCRIPT_API int32_t spark_terrain_get_seed(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_terrain_get_world_units_per_texture_repeat(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_terrain_get_mesh_albedo(const SparkGameComponent* component, SparkVector3* outMeshAlbedo);
SPARK_SCRIPT_API void spark_terrain_set_height_scale(SparkGameComponent* component, float v);
SPARK_SCRIPT_API void spark_terrain_set_noise_scale(SparkGameComponent* component, float v);
SPARK_SCRIPT_API void spark_terrain_set_seed(SparkGameComponent* component, uint32_t v);
SPARK_SCRIPT_API void spark_terrain_reset_heights_to_procedural(SparkGameComponent* component, SparkGameObject* owner);
SPARK_SCRIPT_API void spark_terrain_regenerate_mesh(SparkGameComponent* component, SparkGameObject* owner);
SPARK_SCRIPT_API void spark_terrain_apply_height_brush_local(SparkGameComponent* component, SparkGameObject* owner, const SparkVector2* centerXZ, float radiusXZ, float deltaY);
SPARK_SCRIPT_API void spark_terrain_apply_height_brush_world(SparkGameComponent* component, SparkGameObject* owner, const SparkVector3* centerWorld, float radiusWorld, float deltaY);

SPARK_SCRIPT_API int32_t spark_tilemap_autotile_get_layer_index(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_tilemap_autotile_get_rebuild_on_update(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_autotile_set_rebuild_on_update(SparkGameComponent* component, int enabled);
SPARK_SCRIPT_API void spark_tilemap_autotile_request_rebuild(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_autotile_clear_rebuild_request(SparkGameComponent* component);

SPARK_SCRIPT_API int spark_tilemap_gameplay_grid_get_auto_rebake(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_gameplay_grid_set_auto_rebake(SparkGameComponent* component, int enabled);
SPARK_SCRIPT_API void spark_tilemap_gameplay_grid_request_rebake(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_gameplay_grid_rebake_if_needed(SparkGameComponent* component, SparkGameObject* owner);

SPARK_SCRIPT_API void spark_tilemap_map_source_set_tmx_path(SparkGameComponent* component, const char* path);
SPARK_SCRIPT_API void spark_tilemap_map_source_set_spark_map_path(SparkGameComponent* component, const char* path);
SPARK_SCRIPT_API float spark_tilemap_map_source_get_pixels_per_world_unit(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_map_source_set_pixels_per_world_unit(SparkGameComponent* component, float value);
SPARK_SCRIPT_API int spark_tilemap_map_source_get_import_on_attach(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_map_source_set_import_on_attach(SparkGameComponent* component, int enabled);
SPARK_SCRIPT_API int spark_tilemap_map_source_get_hot_reload(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_map_source_set_hot_reload(SparkGameComponent* component, int enabled);

SPARK_SCRIPT_API int spark_tilemap_object_gizmo_get_draw_gizmos(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_tilemap_object_gizmo_get_draw_runtime_markers(const SparkGameComponent* component);

SPARK_SCRIPT_API int32_t spark_tilemap_object_layer_get_add_object_layer(SparkGameComponent* component, const char* name);
SPARK_SCRIPT_API void spark_tilemap_object_layer_remove_object_layer(SparkGameComponent* component, uint32_t layerIndex);
SPARK_SCRIPT_API int32_t spark_tilemap_object_layer_get_add_marker(SparkGameComponent* component, uint32_t layerIndex, int marker);
SPARK_SCRIPT_API void spark_tilemap_object_layer_clear_markers(SparkGameComponent* component, uint32_t layerIndex);
SPARK_SCRIPT_API int spark_tilemap_object_layer_is_remove_marker(SparkGameComponent* component, uint32_t layerIndex, uint32_t markerId);

SPARK_SCRIPT_API int spark_tilemap_object_spawn_get_spawn_on_attach(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_object_spawn_set_spawn_on_attach(SparkGameComponent* component, int enabled);

SPARK_SCRIPT_API float spark_tilemap_tile_animator_get_animation_time_seconds(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_tile_animator_set_animation_time_seconds(SparkGameComponent* component, float seconds);
SPARK_SCRIPT_API void spark_tilemap_tile_animator_reset_animation_time(SparkGameComponent* component);
SPARK_SCRIPT_API int spark_tilemap_tile_animator_is_playing(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_tilemap_tile_animator_set_playing(SparkGameComponent* component, int play);

SPARK_SCRIPT_API int spark_water_body_get_mode(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_water_body_get_water_level_y(const SparkGameComponent* component);
SPARK_SCRIPT_API int spark_water_body_get_wave_preset_id(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_water_body_get_wave_time_seconds(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_water_body_get_wave_time_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_water_body_get_surface_tile_anchor_x_z(const SparkGameComponent* component, SparkVector2* outSurfaceTileAnchorXZ);
SPARK_SCRIPT_API void spark_water_body_get_mesh_albedo(const SparkGameComponent* component, SparkVector3* outMeshAlbedo);
SPARK_SCRIPT_API void spark_water_body_get_deep_color(const SparkGameComponent* component, SparkVector3* outDeepColor);
SPARK_SCRIPT_API float spark_water_body_get_absorption(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_water_body_get_foam_strength(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_water_body_get_detail_normal_strength(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_water_body_get_shoreline_foam_strength(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_water_body_get_shoreline_foam_max_depth(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_water_body_set_mode(SparkGameComponent* component, int value);
SPARK_SCRIPT_API void spark_water_body_set_water_level_y(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_water_body_set_wave_preset_id(SparkGameComponent* component, int value);
SPARK_SCRIPT_API void spark_water_body_set_mesh_albedo(SparkGameComponent* component, const SparkVector3* value);
SPARK_SCRIPT_API void spark_water_body_set_deep_color(SparkGameComponent* component, const SparkVector3* value);
SPARK_SCRIPT_API void spark_water_body_set_absorption(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_water_body_set_foam_strength(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_water_body_set_detail_normal_strength(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_water_body_set_shoreline_foam_strength(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_water_body_set_shoreline_foam_max_depth(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_water_body_set_ssr_enabled(SparkGameComponent* component, int enabled);
SPARK_SCRIPT_API void spark_water_body_set_wave_time_scale(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_water_body_set_wave_amplitude_scale(SparkGameComponent* component, float value);
SPARK_SCRIPT_API void spark_water_body_set_wave_speed_scale(SparkGameComponent* component, float value);
SPARK_SCRIPT_API float spark_water_body_get_wave_amplitude_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API float spark_water_body_get_wave_speed_scale(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_water_body_set_swell_travel_direction_world(SparkGameComponent* component, const SparkVector2* directionWorldXZ);
SPARK_SCRIPT_API void spark_water_body_clear_swell_travel_direction_override(SparkGameComponent* component);
SPARK_SCRIPT_API void spark_water_body_set_clipmap_camera_world(SparkGameComponent* component, const SparkVector3* worldPosition);
SPARK_SCRIPT_API void spark_water_body_clear_clipmap_camera_override(SparkGameComponent* component);

SPARK_SCRIPT_API int spark_scene_spatial_policy_get_partition_kind(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_scene_spatial_policy_set_partition_kind(SparkGameComponent* component, int k);

SPARK_SCRIPT_API void spark_spawn_point2_d_set_spawn_name(SparkGameComponent* component, const char* name);
SPARK_SCRIPT_API float spark_spawn_point2_d_get_facing_radians(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_spawn_point2_d_set_facing_radians(SparkGameComponent* component, float radians);
SPARK_SCRIPT_API int spark_spawn_point2_d_get_use_transform_facing(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_spawn_point2_d_set_use_transform_facing(SparkGameComponent* component, int value);
SPARK_SCRIPT_API int spark_spawn_point2_d_get_team_id(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_spawn_point2_d_set_team_id(SparkGameComponent* component, int id);

SPARK_SCRIPT_API void spark_spawn_point_set_spawn_name(SparkGameComponent* component, const char* name);

SPARK_SCRIPT_API int spark_time_of_day_driver_is_enabled(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_time_of_day_driver_set_enabled(SparkGameComponent* component, int e);
SPARK_SCRIPT_API int spark_time_of_day_driver_is_looping(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_time_of_day_driver_set_looping(SparkGameComponent* component, int l);
SPARK_SCRIPT_API float spark_time_of_day_driver_get_day_length_seconds(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_time_of_day_driver_set_day_length_seconds(SparkGameComponent* component, float s);
SPARK_SCRIPT_API float spark_time_of_day_driver_get_time_of_day(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_time_of_day_driver_set_time_of_day(SparkGameComponent* component, float t);
SPARK_SCRIPT_API int32_t spark_time_of_day_driver_get_priority(const SparkGameComponent* component);
SPARK_SCRIPT_API void spark_time_of_day_driver_set_priority(SparkGameComponent* component, int32_t p);
