using System.Text;

namespace Spark.Bindings.Generator;

/// <summary>Generates <see cref="AnimationEventReceiverComponent"/> mirror + callback registry (not expressible via generic interop codegen).</summary>
internal static class AnimationEventMirrorCodegen
{
    private const string ReceiverClass = "AnimationEventReceiverComponent";

    public static bool EmitIfNeeded(
        string className,
        List<InteropFunction> functions,
        ComponentBindingManifest manifest,
        string outputDir)
    {
        if (!className.Equals(ReceiverClass, StringComparison.Ordinal))
        {
            return false;
        }

        var prefix = manifest.PrefixToClass.FirstOrDefault(kv => kv.Value.Class == className).Key ?? "anim_event_receiver";
        var fns = functions.Where(f => manifest.MatchPrefix(f.Name) == prefix).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated /> — animation event callbacks via ComponentMirrorCodegen");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Spark.Bindings.Components;");
        sb.AppendLine();
        sb.AppendLine("public readonly struct AnimationEventPayload");
        sb.AppendLine("{");
        sb.AppendLine("    public string EventName { get; init; }");
        sb.AppendLine("    public uint ClipIndex { get; init; }");
        sb.AppendLine("    public float TimeSeconds { get; init; }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public delegate void AnimationEventCallback(GameObject owner, in AnimationEventPayload payload);");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Mirrors C++ <c>AnimationEventReceiverComponent</c> interop.</summary>");
        sb.AppendLine($"public sealed partial class {ReceiverClass} : GameComponentHandle");
        sb.AppendLine("{");
        sb.AppendLine($"    internal {ReceiverClass}(nint handle)");
        sb.AppendLine("        : base(handle) { }");
        sb.AppendLine();

        foreach (var fn in fns)
        {
            if (fn.Name.Contains("set_callback", StringComparison.Ordinal))
            {
                continue;
            }

            if (fn.Name.EndsWith("_clear_markers", StringComparison.Ordinal))
            {
                sb.AppendLine("    public void ClearMarkers()");
                sb.AppendLine("    {");
                sb.AppendLine("        unsafe");
                sb.AppendLine("        {");
                sb.AppendLine($"            Native.{fn.Name}(InteropPtr.Component(Handle));");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else if (fn.Name.Contains("_import_from_skeleton", StringComparison.Ordinal))
            {
                sb.AppendLine("    public void ImportFromSkeleton(GameComponentHandle animator)");
                sb.AppendLine("    {");
                sb.AppendLine("        unsafe");
                sb.AppendLine("        {");
                sb.AppendLine(
                    $"            Native.{fn.Name}(InteropPtr.Component(Handle), InteropPtr.Component(animator.Handle));");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        sb.AppendLine("    public void SetCallback(AnimationEventCallback? callback)");
        sb.AppendLine("    {");
        sb.AppendLine("        AnimationEventCallbackRegistry.Set(Handle, callback);");
        sb.AppendLine("        unsafe");
        sb.AppendLine("        {");
        sb.AppendLine("            var fn = callback is null");
        sb.AppendLine("                ? IntPtr.Zero");
        sb.AppendLine("                : Marshal.GetFunctionPointerForDelegate(AnimationEventCallbackRegistry.NativeCallback);");
        sb.AppendLine("            Native.spark_anim_event_receiver_set_callback(");
        sb.AppendLine("                InteropPtr.Component(Handle),");
        sb.AppendLine("                fn,");
        sb.AppendLine("                (void*)Handle);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var path = Path.Combine(outputDir, $"{ReceiverClass}.g.cs");
        File.WriteAllText(path, sb.ToString());
        Console.WriteLine($"Generated component mirror -> {path}");
        return true;
    }

    public static void EmitSharedRegistry(string outputDir)
    {
        var path = Path.Combine(outputDir, "AnimationEventCallbackRegistry.g.cs");
        const string source = """
            // <auto-generated /> — animation event callbacks via ComponentMirrorCodegen
            #nullable enable

            using System.Collections.Generic;

            namespace Spark.Bindings.Components;

            internal static unsafe class AnimationEventCallbackRegistry
            {
                private static readonly Dictionary<nint, AnimationEventCallback> Callbacks = new();
                private static readonly SparkAnimationEventCallbackFn NativeCallbackImpl = OnNativeCallback;

                public static SparkAnimationEventCallbackFn NativeCallback => NativeCallbackImpl;

                public static void Set(nint receiverHandle, AnimationEventCallback? callback)
                {
                    if (callback is null)
                    {
                        Callbacks.Remove(receiverHandle);
                        return;
                    }

                    Callbacks[receiverHandle] = callback;
                }

                private static void OnNativeCallback(void* userData, SparkGameObject* owner, SparkAnimationEventPayload* payload)
                {
                    var receiverHandle = (nint)userData;
                    if (!Callbacks.TryGetValue(receiverHandle, out var callback) || payload is null)
                    {
                        return;
                    }

                    var ownerObj = owner is null ? null! : new GameObject(InteropPtr.From(owner));
                    var name = payload->eventName is null
                        ? string.Empty
                        : System.Runtime.InteropServices.Marshal.PtrToStringUTF8((nint)payload->eventName) ?? string.Empty;
                    var evt = new AnimationEventPayload
                    {
                        EventName = name,
                        ClipIndex = payload->clipIndex,
                        TimeSeconds = payload->timeSeconds,
                    };
                    callback(ownerObj, in evt);
                }
            }
            """;

        File.WriteAllText(path, source);
        Console.WriteLine($"Generated callback registry -> {path}");
    }
}
