using System.Globalization;
using System.Text;

namespace Spark.Bindings.Generator;

internal static class ComponentMirrorCodegen
{
    public static void Generate(
        IReadOnlyList<InteropFunction> functions,
        ComponentBindingManifest manifest,
        string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        var byPrefix = new Dictionary<string, List<InteropFunction>>();
        foreach (var fn in functions)
        {
            if (!fn.IsComponentApi)
            {
                continue;
            }

            var prefix = manifest.MatchPrefix(fn.Name);
            if (prefix is null)
            {
                continue;
            }

            if (!byPrefix.TryGetValue(prefix, out var group))
            {
                group = [];
                byPrefix[prefix] = group;
            }

            group.Add(fn);
        }

        var byClass = new Dictionary<string, (PrefixBinding Binding, List<string> Prefixes, List<InteropFunction> Functions)>();
        foreach (var (prefix, fns) in byPrefix)
        {
            if (!manifest.PrefixToClass.TryGetValue(prefix, out var binding))
            {
                continue;
            }

            if (!byClass.TryGetValue(binding.Class, out var bucket))
            {
                bucket = (binding, [], []);
                byClass[binding.Class] = bucket;
            }

            bucket.Prefixes.Add(prefix);
            bucket.Functions.AddRange(fns);
        }

        var emittedClasses = new HashSet<string>();
        foreach (var (className, bucket) in byClass)
        {
            if (manifest.SkipMirrorCodegenClasses.Contains(className))
            {
                if (AnimationEventMirrorCodegen.EmitIfNeeded(className, bucket.Functions, manifest, outputDir))
                {
                    emittedClasses.Add(className);
                }

                continue;
            }

            var primaryPrefix = bucket.Prefixes.OrderByDescending(static p => p.Length).First();
            var path = Path.Combine(outputDir, $"{className}.g.cs");
            var source = EmitClass(primaryPrefix, bucket.Binding, bucket.Functions, manifest);
            File.WriteAllText(path, source);
            emittedClasses.Add(className);
            Console.WriteLine($"Generated component mirror -> {path}");
        }

        AnimationEventMirrorCodegen.EmitSharedRegistry(outputDir);

        // Remove stale generated files for classes we no longer emit.
        foreach (var existing in Directory.EnumerateFiles(outputDir, "*.g.cs"))
        {
            var fileName = Path.GetFileName(existing);
            var className = fileName.EndsWith(".g.cs", StringComparison.Ordinal)
                ? fileName[..^5]
                : Path.GetFileNameWithoutExtension(fileName);
            if (!emittedClasses.Contains(className)
                && className is not "AnimationEventCallbackRegistry")
            {
                File.Delete(existing);
            }
        }
    }

    private static string EmitClass(string interopPrefix, PrefixBinding binding, List<InteropFunction> functions, ComponentBindingManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated /> — from SparkInterop.h via ComponentMirrorCodegen");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {binding.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Mirrors C++ component API via <c>spark_*</c> interop.</summary>");

        var usesHandleBase = binding.Base.Equals("GameComponentHandle", StringComparison.Ordinal);
        if (usesHandleBase)
        {
            sb.AppendLine($"public sealed partial class {binding.Class} : GameComponentHandle");
            sb.AppendLine("{");
            sb.AppendLine($"    internal {binding.Class}(nint handle)");
            sb.AppendLine("        : base(handle) { }");
        }
        else
        {
            sb.AppendLine($"public sealed partial class {binding.Class}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly nint _handle;");
            sb.AppendLine($"    internal {binding.Class}(nint handle) => _handle = handle;");
            sb.AppendLine("    public nint Handle => _handle;");
        }

        var receiver = usesHandleBase ? "Handle" : "_handle";
        var grouped = GroupMembers(manifest, functions);
        foreach (var member in grouped)
        {
            sb.AppendLine();
            sb.Append(member.Emit(receiver, usesHandleBase));
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static List<MemberEmitter> GroupMembers(ComponentBindingManifest manifest, List<InteropFunction> functions)
    {
        var emitters = new List<MemberEmitter>();
        var bySuffix = functions
            .Select(f =>
            {
                var prefix = manifest.MatchPrefix(f.Name) ?? "";
                return (Fn: f, Suffix: StripPrefix(f.Name, prefix));
            })
            .Where(x => x.Suffix.Length > 0)
            .ToList();

        var getSet = new Dictionary<string, (InteropFunction? Get, InteropFunction? Set)>();
        foreach (var (fn, suffix) in bySuffix)
        {
            if (suffix.StartsWith("get_", StringComparison.Ordinal))
            {
                var key = suffix["get_".Length..];
                getSet.TryGetValue(key, out var pair);
                getSet[key] = (fn, pair.Set);
            }
            else if (suffix.StartsWith("set_", StringComparison.Ordinal))
            {
                var key = suffix["set_".Length..];
                getSet.TryGetValue(key, out var pair);
                getSet[key] = (pair.Get, fn);
            }
        }

        var consumed = new HashSet<string>();
        foreach (var (key, (get, set)) in getSet)
        {
            if (get is not null && set is not null)
            {
                if (get.ReturnType == "void" && TryGetOutVector(get, out var vecType) && set.Parameters.Count == 2)
                {
                    emitters.Add(new VectorPropertyEmitter(key, get, set, vecType));
                    consumed.Add(get.Name);
                    consumed.Add(set.Name);
                    continue;
                }

                if (CanBeProperty(get, set))
                {
                    emitters.Add(new PropertyEmitter(key, get, set));
                    consumed.Add(get.Name);
                    consumed.Add(set.Name);
                }
            }
        }

        foreach (var (fn, suffix) in bySuffix)
        {
            if (consumed.Contains(fn.Name))
            {
                continue;
            }

            if (ShouldSkipInteropFunction(fn))
            {
                continue;
            }

            if (fn.Name.Contains("_get_", StringComparison.Ordinal) && fn.ReturnType == "void")
            {
                emitters.Add(new OutGetterMethodEmitter(fn, suffix));
                continue;
            }

            emitters.Add(new MethodEmitter(fn, suffix));
        }

        return emitters;
    }

    private static string StripPrefix(string functionName, string interopPrefix)
    {
        var head = $"spark_{interopPrefix}_";
        return functionName.StartsWith(head, StringComparison.Ordinal)
            ? functionName[head.Length..]
            : "";
    }

    private static bool CanBeProperty(InteropFunction get, InteropFunction set)
    {
        if (get.Parameters.Count != 1 || set.Parameters.Count != 2)
        {
            return false;
        }

        if (get.ReturnType != set.Parameters[1].Type)
        {
            if (!(IsScalarReturn(get.ReturnType) && IsScalarReturn(set.Parameters[1].Type)))
            {
                return false;
            }
        }

        return IsScalarReturn(get.ReturnType) || get.ReturnType is "int" or "uint32_t" or "SparkComponentKind";
    }

    private static bool IsScalarReturn(string ret) =>
        ret is "float" or "double" or "int" or "uint32_t" or "uint64_t" or "uint16_t" or "size_t"
        || IsSparkEnumType(ret);

    private static bool ShouldSkipInteropFunction(InteropFunction fn) =>
        fn.Parameters.Any(static p => p.Type.Contains("CallbackFn", StringComparison.Ordinal));

    private static bool IsSparkEnumType(string type)
    {
        if (!type.StartsWith("Spark", StringComparison.Ordinal) || type.Contains('*', StringComparison.Ordinal))
        {
            return false;
        }

        return type is not (
            "SparkGameObject" or "SparkGameComponent" or "SparkGameWorld"
            or "SparkVector2" or "SparkVector3" or "SparkVector4" or "SparkQuaternion"
            or "SparkMatrix4" or "SparkAnimationEventPayload" or "SparkSpriteAnimationClip");
    }

    private static bool TryGetOutVector(InteropFunction get, out string vectorType)
    {
        vectorType = "";
        if (get.Parameters.Count != 2)
        {
            return false;
        }

        var outParam = get.Parameters[1];
        if (!outParam.Type.Contains('*', StringComparison.Ordinal))
        {
            return false;
        }

        if (outParam.Type.Contains("SparkVector3", StringComparison.Ordinal))
        {
            vectorType = "Vector3";
            return true;
        }

        if (outParam.Type.Contains("SparkVector2", StringComparison.Ordinal))
        {
            vectorType = "Vector2";
            return true;
        }

        if (outParam.Type.Contains("SparkVector4", StringComparison.Ordinal))
        {
            vectorType = "Vector4";
            return true;
        }

        return false;
    }

    private sealed class VectorPropertyEmitter : MemberEmitter
    {
        private readonly string _key;
        private readonly InteropFunction _get;
        private readonly InteropFunction _set;
        private readonly string _vectorType;

        public VectorPropertyEmitter(string key, InteropFunction get, InteropFunction set, string vectorType)
        {
            _key = key;
            _get = get;
            _set = set;
            _vectorType = vectorType;
        }

        public override string Emit(string receiverField, bool handleBase)
        {
            var ptr = $"InteropPtr.Component({receiverField})";
            var name = ToPascalCase(_key);
            var native = _vectorType switch
            {
                "Vector3" => "SparkVector3",
                "Vector2" => "SparkVector2",
                "Vector4" => "SparkVector4",
                _ => "SparkVector3",
            };
            var sb = new StringBuilder();
            sb.AppendLine($"    public {_vectorType} {name}");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe");
            sb.AppendLine("            {");
            sb.AppendLine($"                {native} v;");
            sb.AppendLine($"                Native.{_get.Name}({ptr}, &v);");
            sb.AppendLine($"                return {_vectorType}.FromNative(v);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe");
            sb.AppendLine("            {");
            sb.AppendLine($"                var v = value.ToNative();");
            sb.AppendLine($"                Native.{_set.Name}({ptr}, &v);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            return sb.ToString();
        }
    }

    private abstract class MemberEmitter
    {
        public abstract string Emit(string receiverField, bool handleBase);
    }

    private sealed class PropertyEmitter : MemberEmitter
    {
        private readonly string _key;
        private readonly InteropFunction _get;
        private readonly InteropFunction _set;

        public PropertyEmitter(string key, InteropFunction get, InteropFunction set)
        {
            _key = key;
            _get = get;
            _set = set;
        }

        public override string Emit(string receiverField, bool handleBase)
        {
            var name = ToPascalCase(_key);
            var sb = new StringBuilder();
            var ptr = handleBase ? $"InteropPtr.Component({receiverField})" : $"InteropPtr.Component({receiverField})";

            if (_get.ReturnType == "int" && (_key.Contains("enabled", StringComparison.Ordinal) ||
                                             _key.StartsWith("is_", StringComparison.Ordinal)))
            {
                sb.AppendLine($"    public bool {name}");
                sb.AppendLine("    {");
                sb.AppendLine("        get");
                sb.AppendLine("        {");
                sb.AppendLine("            unsafe");
                sb.AppendLine("            {");
                sb.AppendLine($"                return Native.{_get.Name}({ptr}) != 0;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine("        set");
                sb.AppendLine("        {");
                sb.AppendLine("            unsafe");
                sb.AppendLine("            {");
                sb.AppendLine($"                Native.{_set.Name}({ptr}, value ? 1 : 0);");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                return sb.ToString();
            }

            var csType = MapReturnType(_get.ReturnType);
            sb.AppendLine($"    public {csType} {name}");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe");
            sb.AppendLine("            {");
            sb.AppendLine($"                return Native.{_get.Name}({ptr});");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        set");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe");
            sb.AppendLine("            {");
            sb.AppendLine(EmitSetValue(_set, ptr, "value"));
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            return sb.ToString();
        }
    }

    private sealed class OutGetterMethodEmitter : MemberEmitter
    {
        private readonly InteropFunction _fn;
        private readonly string _suffix;

        public OutGetterMethodEmitter(InteropFunction fn, string suffix)
        {
            _fn = fn;
            _suffix = suffix;
        }

        public override string Emit(string receiverField, bool handleBase)
        {
            var ptr = $"InteropPtr.Component({receiverField})";
            var outParams = _fn.Parameters.Skip(1)
                .Where(static p => p.Type.Contains('*', StringComparison.Ordinal))
                .ToList();
            if (outParams.Count >= 2 && outParams.All(static p => p.Type is "float*" or "double*"))
            {
                var methodName = ToPascalCase(_suffix.Replace("get_", "", StringComparison.Ordinal));
                var multi = new StringBuilder();
                multi.AppendLine($"    public (float {ToPascalCase(outParams[0].Name.Replace("out", "", StringComparison.OrdinalIgnoreCase))}, float {ToPascalCase(outParams[1].Name.Replace("out", "", StringComparison.OrdinalIgnoreCase))}) {methodName}()");
                multi.AppendLine("    {");
                multi.AppendLine("        unsafe");
                multi.AppendLine("        {");
                multi.AppendLine("            float a;");
                multi.AppendLine("            float b;");
                multi.AppendLine($"            Native.{_fn.Name}({ptr}, &a, &b);");
                multi.AppendLine("            return (a, b);");
                multi.AppendLine("        }");
                multi.AppendLine("    }");
                return multi.ToString();
            }

            var outParam = outParams.FirstOrDefault(p => p.Name.StartsWith("out", StringComparison.OrdinalIgnoreCase))
                           ?? outParams.FirstOrDefault();
            if (outParam is null)
            {
                return new MethodEmitter(_fn, _suffix).Emit(receiverField, handleBase);
            }

            var name = ToPascalCase(_suffix.Replace("get_", "", StringComparison.Ordinal));
            var csType = MapPointeeType(outParam.Type);
            var sb = new StringBuilder();
            sb.AppendLine($"    public {csType} {name}");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe");
            sb.AppendLine("            {");
            if (csType == "Vector3")
            {
                sb.AppendLine("                SparkVector3 v;");
                sb.AppendLine($"                Native.{_fn.Name}({ptr}, &v);");
                sb.AppendLine("                return Vector3.FromNative(v);");
            }
            else if (csType == "Vector2")
            {
                sb.AppendLine("                SparkVector2 v;");
                sb.AppendLine($"                Native.{_fn.Name}({ptr}, &v);");
                sb.AppendLine("                return Vector2.FromNative(v);");
            }
            else
            {
                sb.AppendLine($"                Native.{_fn.Name}({ptr}, out var v);");
                sb.AppendLine("                return v;");
            }

            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            return sb.ToString();
        }
    }

    private sealed class MethodEmitter : MemberEmitter
    {
        private readonly InteropFunction _fn;
        private readonly string _suffix;

        public MethodEmitter(InteropFunction fn, string suffix)
        {
            _fn = fn;
            _suffix = suffix;
        }

        public override string Emit(string receiverField, bool handleBase)
        {
            var ptr = $"InteropPtr.Component({receiverField})";
            var methodName = ToPascalCase(_suffix);
            var sb = new StringBuilder();
            var parameters = _fn.Parameters.Skip(1).ToList();
            var paramDecl = string.Join(", ", parameters.Select(p => $"{MapParamType(p)} {ToCamelCase(p.Name)}"));
            var returnType = _fn.ReturnType == "void" ? "void" : MapReturnType(_fn.ReturnType);
            if (_fn.ReturnType == "int" && methodName.StartsWith("Set", StringComparison.Ordinal))
            {
                returnType = "bool";
            }

            sb.AppendLine($"    public {returnType} {methodName}({paramDecl})");
            sb.AppendLine("    {");
            sb.AppendLine("        unsafe");
            sb.AppendLine("        {");

            var hasString = parameters.Any(static p =>
                p.Type.Contains("const char", StringComparison.Ordinal) || p.Type.Contains("char*", StringComparison.Ordinal));
            if (hasString)
            {
                var stringParam = parameters.First(p =>
                    p.Type.Contains("const char", StringComparison.Ordinal) || p.Type.Contains("char*", StringComparison.Ordinal));
                var stringName = ToCamelCase(stringParam.Name);
                var needsBool = returnType == "bool" && _fn.ReturnType == "int";
                var needsValue = returnType != "void" && !needsBool;
                if (needsBool)
                {
                    sb.AppendLine("            var result = 0;");
                }
                else if (needsValue)
                {
                    sb.AppendLine($"            {returnType} result = default;");
                }

                sb.AppendLine($"            InteropUtf8.WithUtf8({stringName}, ptr =>");
                sb.AppendLine("            {");
                EmitMethodCallBody(sb, ptr, parameters, stringName, "ptr", needsBool || needsValue, needsValue);
                sb.AppendLine("            });");
                if (needsBool)
                {
                    sb.AppendLine("            return result != 0;");
                }
                else if (needsValue)
                {
                    sb.AppendLine("            return result;");
                }
            }
            else
            {
                var needsBool = returnType == "bool" && _fn.ReturnType == "int";
                if (needsBool)
                {
                    sb.AppendLine("            var result = 0;");
                }

                foreach (var p in parameters)
                {
                    if (p.Type.Contains("SparkQuaternion", StringComparison.Ordinal))
                    {
                        sb.AppendLine($"            var {ToCamelCase(p.Name)}Native = {ToCamelCase(p.Name)};");
                    }
                    else if (NeedsNativeBlit(p.Type))
                    {
                        sb.AppendLine($"            var {ToCamelCase(p.Name)}Native = {ToCamelCase(p.Name)}.ToNative();");
                    }
                }

                EmitMethodCallBody(sb, ptr, parameters, null, null, needsBool);
                if (needsBool)
                {
                    sb.AppendLine("            return result != 0;");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            return sb.ToString();
        }

        private void EmitMethodCallBody(
            StringBuilder sb,
            string ptr,
            List<InteropParameter> parameters,
            string? stringParamName,
            string? utf8PtrName,
            bool assignResult = false,
            bool assignTypedResult = false)
        {
            var args = new List<string> { ptr };
            foreach (var p in parameters)
            {
                if (stringParamName is not null && ToCamelCase(p.Name) == stringParamName)
                {
                    args.Add($"(sbyte*){utf8PtrName}");
                }
                else
                {
                    args.Add(EmitArg(p));
                }
            }

            if (assignResult)
            {
                sb.AppendLine($"                result = Native.{_fn.Name}({string.Join(", ", args)});");
            }
            else if (_fn.ReturnType == "void")
            {
                sb.AppendLine($"                Native.{_fn.Name}({string.Join(", ", args)});");
            }
            else
            {
                sb.AppendLine($"                return Native.{_fn.Name}({string.Join(", ", args)});");
            }
        }
    }

    private static bool NeedsNativeBlit(string type) =>
        type.Contains("SparkVector3", StringComparison.Ordinal)
        || type.Contains("SparkVector2", StringComparison.Ordinal)
        || type.Contains("SparkVector4", StringComparison.Ordinal)
        || type.Contains("SparkQuaternion", StringComparison.Ordinal);

    private static string EmitSetValue(InteropFunction set, string ptr, string valueExpr)
    {
        var valueParam = set.Parameters[1];
        if (valueParam.Type.Contains("SparkVector3", StringComparison.Ordinal))
        {
            return $"                var native = {valueExpr}.ToNative();\n                Native.{set.Name}({ptr}, &native);";
        }

        if (valueParam.Type.Contains("SparkVector4", StringComparison.Ordinal))
        {
            return $"                var native = {valueExpr}.ToNative();\n                Native.{set.Name}({ptr}, &native);";
        }

        if (valueParam.Type.Contains("SparkVector2", StringComparison.Ordinal))
        {
            return $"                var native = {valueExpr}.ToNative();\n                Native.{set.Name}({ptr}, &native);";
        }

        if (valueParam.Type.Contains("SparkQuaternion", StringComparison.Ordinal))
        {
            return $"                var native = {valueExpr};\n                Native.{set.Name}({ptr}, &native);";
        }

        if (valueParam.Type.Contains("SparkGameObject", StringComparison.Ordinal))
        {
            return $"                Native.{set.Name}({ptr}, InteropPtr.Object({valueExpr}.Handle));";
        }

        return $"                Native.{set.Name}({ptr}, {valueExpr});";
    }

    private static string EmitArg(InteropParameter p)
    {
        if (p.Type.Contains("const char", StringComparison.Ordinal) || p.Type.Contains("char*", StringComparison.Ordinal))
        {
            return $"(sbyte*)0 /* string {p.Name} */";
        }

        if (p.Type.Contains("SparkVector3", StringComparison.Ordinal))
        {
            return $"&{ToCamelCase(p.Name)}Native";
        }

        if (p.Type.Contains("SparkVector2", StringComparison.Ordinal))
        {
            return $"&{ToCamelCase(p.Name)}Native";
        }

        if (p.Type.Contains("SparkVector4", StringComparison.Ordinal))
        {
            return $"&{ToCamelCase(p.Name)}Native";
        }

        if (p.Type.Contains("SparkQuaternion", StringComparison.Ordinal))
        {
            return $"&{ToCamelCase(p.Name)}Native";
        }

        if (p.Type.Contains("SparkSpriteAnimationClip", StringComparison.Ordinal))
        {
            return $"(SparkSpriteAnimationClip*){ToCamelCase(p.Name)}";
        }

        if (p.Type.Contains("SparkGameWorld", StringComparison.Ordinal))
        {
            return $"InteropPtr.World({ToCamelCase(p.Name)}.Handle)";
        }

        if (p.Type.Contains("SparkGameObject", StringComparison.Ordinal))
        {
            return $"InteropPtr.Object({ToCamelCase(p.Name)}.Handle)";
        }

        if (p.Type.Contains("SparkGameComponent", StringComparison.Ordinal))
        {
            return $"InteropPtr.Component({ToCamelCase(p.Name)}.Handle)";
        }

        return ToCamelCase(p.Name);
    }

    private static string MapReturnType(string ret)
    {
        if (IsSparkEnumType(ret))
        {
            return ret;
        }

        return ret switch
        {
            "float" => "float",
            "double" => "double",
            "int" => "int",
            "uint32_t" => "uint",
            "uint64_t" => "ulong",
            "uint16_t" => "ushort",
            "size_t" => "nuint",
            "void" => "void",
            _ => "int",
        };
    }

    private static string MapParamType(InteropParameter p)
    {
        if (p.Type.Contains("SparkGameWorld", StringComparison.Ordinal))
        {
            return "GameWorld";
        }

        if (p.Type.Contains("SparkGameObject", StringComparison.Ordinal))
        {
            return "GameObject";
        }

        if (p.Type.Contains("SparkGameComponent", StringComparison.Ordinal))
        {
            return "GameComponentHandle";
        }

        if (p.Type.Contains("const char", StringComparison.Ordinal) || p.Type.Contains("char*", StringComparison.Ordinal))
        {
            return "string";
        }

        if (p.Type.Contains("SparkVector3", StringComparison.Ordinal))
        {
            return "in Vector3";
        }

        if (p.Type.Contains("SparkVector2", StringComparison.Ordinal))
        {
            return "in Vector2";
        }

        if (p.Type.Contains("SparkVector4", StringComparison.Ordinal))
        {
            return "in Vector4";
        }

        if (p.Type.Contains("SparkQuaternion", StringComparison.Ordinal))
        {
            return "in SparkQuaternion";
        }

        if (p.Type.Contains("SparkSpriteAnimationClip", StringComparison.Ordinal))
        {
            return "nint";
        }

        if (IsSparkEnumType(p.Type))
        {
            return p.Type;
        }

        return p.Type switch
        {
            "float" => "float",
            "double" => "double",
            "int" => "int",
            "uint32_t" => "uint",
            "uint64_t" => "ulong",
            "uint16_t" => "ushort",
            "size_t" => "nuint",
            _ => "int",
        };
    }

    private static string MapPointeeType(string type)
    {
        if (type.Contains("SparkVector3", StringComparison.Ordinal))
        {
            return "Vector3";
        }

        if (type.Contains("SparkVector2", StringComparison.Ordinal))
        {
            return "Vector2";
        }

        return "float";
    }

    private static string ToPascalCase(string snake)
    {
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(parts.Select(static p =>
            char.ToUpper(p[0], CultureInfo.InvariantCulture) + p[1..]));
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        if (name.Equals("object", StringComparison.Ordinal))
        {
            return "gameObject";
        }

        var pascal = ToPascalCase(name);
        return char.ToLower(pascal[0], CultureInfo.InvariantCulture) + pascal[1..];
    }
}
