#pragma once

#include "spark/config.hpp"
#include "spark/core/Array.hpp"
#include "spark/core/Utf8String.hpp"
#include "spark/ecs/Ecs.hpp"
#include "spark/engine/Engine.hpp"
#include "spark/engine/Game.hpp"
#include "spark/memory/UniquePtr.hpp"
#include "spark/engine/IEngineContext.hpp"
#include "spark/engine/SceneRenderParams.hpp"
#include "spark/math/Constants.hpp"
#include "spark/render/scene/SceneGroundExtent.hpp"
#include "spark/math/Matrix4.hpp"
#include "spark/math/Quaternion.hpp"
#include "spark/math/Vector2.hpp"
#include "spark/math/Vector3.hpp"
#include "spark/math/Vector4.hpp"
#include "spark/memory/SharedPtr.hpp"
#include "spark/animation/Skeleton.hpp"
#include "spark/scene/CharacterCameraRig.hpp"
#include "spark/scene/FlyCamera.hpp"
#include "spark/scene/GameWorld.hpp"
#include "spark/scene/Mesh.hpp"
#include "spark/scene/SkinnedMesh.hpp"
#include "spark/scene/Texture2D.hpp"
#include "spark/text/Font.hpp"
#include "spark/scene/SceneSubmit.hpp"
#include "spark/ecs/components/ui/GuiCanvasComponent.hpp"
#include "spark/ecs/components/rendering/ParticleEmitterComponent.hpp"
#include "spark/ecs/components/rendering/SpriteComponent.hpp"
#include "spark/ecs/components/rendering/TerrainComponent.hpp"
#include "spark/ecs/components/rendering/TilemapComponent.hpp"
#include "spark/ecs/components/physics/2d/BoxCollider2DComponent.hpp"
#include "spark/ecs/components/physics/2d/CircleCollider2DComponent.hpp"
#include "spark/ecs/components/physics/2d/Rigidbody2DComponent.hpp"
#include "spark/physics/PhysicsWorld2D.hpp"
#include "spark/scene/Camera2D.hpp"
#include "spark/gui/GuiControls.hpp"
#include "spark/gui/GuiScene.hpp"
#include "spark/gui/Widget.hpp"

#include <GLFW/glfw3.h>

#include <algorithm>
#include <cmath>
#include <exception>
#include <format>
#include <iostream>
#include <print>
#include <string>
