<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <RootNamespace>HelloCsGame</RootNamespace>
    <NoWarn>$(NoWarn);CA2255</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Spark.Scripting/Spark.Scripting.csproj" />
  </ItemGroup>
</Project>
