<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Spark.Scripting</RootNamespace>
    <AssemblyName>Spark.Scripting</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../bindings/generated/Spark.Bindings/Spark.Bindings.csproj" />
  </ItemGroup>
</Project>
