#!/usr/bin/env python3
"""Generate per-kind C# component handles and GameObject accessors from SparkInteropComponentKinds.h."""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HDR = ROOT / "include/spark/scripting/SparkInteropComponentKinds.h"
ECS_HPP = ROOT / "include/spark/ecs/Ecs.hpp"
OUT_COMPONENTS = ROOT / "scripting/bindings/generated/Spark.Bindings/Components/Generated"
OUT_COMPONENTS_ROOT = ROOT / "scripting/bindings/generated/Spark.Bindings/Components"
FROM_INTEROP = ROOT / "scripting/bindings/generated/Spark.Bindings/Components/FromInterop"
OUT_GAMEOBJECT = ROOT / "scripting/bindings/generated/Spark.Bindings/GameObject.ComponentAccess.g.cs"
OUT_FACTORY_CPP = ROOT / "src/spark/scripting/SparkInteropComponentFactory.generated.cpp"

# Rich mirrors live outside Generated/ (do not emit duplicate handle files).
SKIP_HANDLE_FILES: set[str] = set()

# Kinds that cannot be default-constructed via AddComponent<T>() (asset / ctor args required).
FACTORY_DENY = {
    "Unknown",
    "Mesh",
    "Collision",
    "Material",
    "MultiMaterial",
    "PointLight",
    "SkinnedMesh",
    "Animator",
    "Sky",
    "Sprite",
    "Tilemap",
    "Terrain",
    "Camera",
    "DirectionalLight",
    "SpotLight",
    "PointLight2D",
    "GltfSceneSource",
    "GltfInstanceNode",
    "WaterBody",
    "Scene2DCompositeView",
}


def parse_ecs_included_kinds() -> set[str]:
    text = ECS_HPP.read_text(encoding="utf-8")
    return set(re.findall(r"/([\w]+)Component\.hpp", text))


def parse_kinds() -> list[str]:
    text = HDR.read_text(encoding="utf-8")
    kinds = re.findall(r"SparkComponentKind_(\w+)", text)
    # drop duplicate matches from comments if any
    seen: set[str] = set()
    ordered: list[str] = []
    for k in kinds:
        if k not in seen:
            seen.add(k)
            ordered.append(k)
    return ordered


def kind_to_cpp_type(kind: str) -> str:
    return f"Spark::{kind}Component"


def kind_to_csharp_class(kind: str) -> str:
    return f"{kind}Component"


def csharp_return_type(kind: str) -> tuple[str, str]:
    cls = kind_to_csharp_class(kind)
    return ("Components.", f"new Components.{cls}(h)")


def interop_generated_classes() -> set[str]:
    if not FROM_INTEROP.is_dir():
        return set()
    return {p.name.replace(".g.cs", "") for p in FROM_INTEROP.glob("*.g.cs")}


def emit_game_component_handle_base() -> None:
    path = OUT_COMPONENTS_ROOT / "GameComponentHandle.g.cs"
    path.write_text(
        """// <auto-generated /> — base handle for mirrored Spark::GameComponent instances.
#nullable enable

namespace Spark.Bindings.Components;

/// <summary>Base handle for mirrored <c>Spark::GameComponent</c> instances.</summary>
public abstract class GameComponentHandle
{
    protected GameComponentHandle(nint handle) => Handle = handle;

    public nint Handle { get; }

    public SparkComponentKind Kind
    {
        get
        {
            unsafe
            {
                return Native.spark_component_get_kind(InteropPtr.Component(Handle));
            }
        }
    }
}
""",
        encoding="utf-8",
    )
    legacy = OUT_COMPONENTS_ROOT / "GameComponentHandle.cs"
    if legacy.is_file():
        legacy.unlink()


def emit_handle_file(kind: str, skip_classes: set[str]) -> None:
    cls = kind_to_csharp_class(kind)
    if cls in skip_classes:
        return
    path = OUT_COMPONENTS / f"{cls}.cs"
    path.write_text(
        f"""// <auto-generated /> — handle for Spark::{cls}. Extend with spark_* APIs in a hand-maintained partial if needed.
#nullable enable

namespace Spark.Bindings.Components;

/// <summary>Mirrors <c>Spark::{cls}</c>.</summary>
public sealed partial class {cls} : GameComponentHandle
{{
    internal {cls}(nint handle)
        : base(handle) {{ }}
}}
""",
        encoding="utf-8",
    )


def emit_gameobject_access(kinds: list[str]) -> None:
    lines = [
        "// <auto-generated /> — TryGet accessors for every SparkComponentKind.",
        "#nullable enable",
        "",
        "namespace Spark.Bindings;",
        "",
        "public sealed partial class GameObject",
        "{",
    ]
    for kind in kinds:
        if kind == "Unknown":
            continue
        enum_member = f"SparkComponentKind.SparkComponentKind_{kind}"
        cls = kind_to_csharp_class(kind)
        ns, factory = csharp_return_type(kind)
        method = f"Get{kind}" if not kind.endswith("2D") else f"Get{kind}"
        # e.g. BoxCollider2D -> GetBoxCollider2D
        lines.append(f"    public {ns}{cls}? {method}() =>")
        lines.append(f"        GetComponent({enum_member}, static h => {factory});")
        lines.append("")
        if kind not in FACTORY_DENY and kind != "Transform":
            type_name = f"{ns}{cls}" if ns else cls
            lines.append(f"    public {type_name}? GetOrAdd{kind}()")
            lines.append("    {")
            lines.append("        unsafe")
            lines.append("        {")
            lines.append(
                f"            var ptr = Native.spark_object_get_or_add_default_component("
                f"InteropPtr.Object(Handle), {enum_member});"
            )
            lines.append(f"            return ptr == null ? null : new {type_name}(InteropPtr.From(ptr));")
            lines.append("        }")
            lines.append("    }")
            lines.append("")

    lines.append("}")
    OUT_GAMEOBJECT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_factory_cpp(kinds: list[str]) -> None:
    ecs_kinds = parse_ecs_included_kinds()
    cases: list[str] = []
    for kind in kinds:
        if kind in FACTORY_DENY or kind not in ecs_kinds:
            continue
        cpp = kind_to_cpp_type(kind)
        cases.append(
            f"        case SparkComponentKind_{kind}:\n"
            f"            return GetOrAddComponent<{cpp}>(object);"
        )
    body = "\n".join(cases)
    OUT_FACTORY_CPP.write_text(
        f"""// <auto-generated /> — included from SparkInteropComponentFactory.cpp
#include "spark/ecs/Ecs.hpp"
#include "spark/ecs/GameObject.hpp"
#include "spark/scripting/SparkInterop.h"

namespace SparkInteropFactory {{

template<typename T>
SparkGameComponent* GetOrAddComponent(Spark::GameObject* object) {{
    if (object == nullptr) {{
        return nullptr;
    }}
    if (Spark::GameComponent* existing = object->TryGetComponentByKind(T::TypeKind)) {{
        return reinterpret_cast<SparkGameComponent*>(existing);
    }}
    return reinterpret_cast<SparkGameComponent*>(object->AddComponent<T>());
}}

SparkGameComponent* DispatchGetOrAddDefault(Spark::GameObject* object, SparkComponentKind kind) {{
    switch (kind) {{
{body}
        default:
            return nullptr;
    }}
}}

}}  // namespace SparkInteropFactory
""",
        encoding="utf-8",
    )


def main() -> int:
    kinds = parse_kinds()
    OUT_COMPONENTS.mkdir(parents=True, exist_ok=True)
    emit_game_component_handle_base()
    from_interop = interop_generated_classes()
    for kind in kinds:
        if kind == "Unknown" or kind in SKIP_HANDLE_FILES:
            continue
        emit_handle_file(kind, from_interop)
    for cls in from_interop:
        stub = OUT_COMPONENTS / f"{cls}.cs"
        if stub.is_file():
            stub.unlink()
    emit_gameobject_access(kinds)
    emit_factory_cpp(kinds)
    print(f"Generated {len([k for k in kinds if k != 'Unknown' and k not in SKIP_HANDLE_FILES])} component handles")
    print(f"Wrote {OUT_GAMEOBJECT}")
    print(f"Wrote {OUT_FACTORY_CPP}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
