#!/usr/bin/env python3
"""Emit Native.Interop.g.cs partial with P/Invoke for all SPARK_SCRIPT_API in SparkInterop.h."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HDR = ROOT / "include/spark/scripting/SparkInterop.h"
HDR_GENERATED = ROOT / "include/spark/scripting/SparkInteropComponentBindings.generated.h"
OUT = ROOT / "scripting/bindings/generated/Spark.Bindings/Native.Interop.g.cs"

DECL_RE = re.compile(
    r"SPARK_SCRIPT_API\s+(?P<ret>[\w\s\*]+?)\s+(?P<name>spark_\w+)\s*\((?P<args>[^;]*)\)\s*;",
)


def map_type(c: str) -> str:
    c = re.sub(r"\s+", " ", c.replace("const ", "").strip())
    table = {
        "void": "void",
        "int": "int",
        "float": "float",
        "double": "float",
        "uint32_t": "uint",
        "uint64_t": "ulong",
        "uint16_t": "ushort",
        "SparkGameComponent*": "SparkGameComponent*",
        "SparkGameObject*": "SparkGameObject*",
        "SparkGameWorld*": "SparkGameWorld*",
        "SparkVector2*": "SparkVector2*",
        "SparkVector3*": "SparkVector3*",
        "SparkVector4*": "SparkVector4*",
        "SparkQuaternion*": "SparkQuaternion*",
        "SparkMatrix4*": "SparkMatrix4*",
        "SparkComponentKind": "SparkComponentKind",
        "SparkGameFlowState": "SparkGameFlowState",
        "SparkGameFlowTriggerSource": "SparkGameFlowTriggerSource",
        "SparkParallaxAxisMode": "SparkParallaxAxisMode",
        "SparkParallaxDriftMode": "SparkParallaxDriftMode",
        "SparkSceneSkyMode": "SparkSceneSkyMode",
        "SparkSceneMeshSlot": "SparkSceneMeshSlot",
        "SparkRigidbodyBodyType2D": "SparkRigidbodyBodyType2D",
        "SparkFrameTiming*": "SparkFrameTiming*",
        "SparkEngineContext*": "SparkEngineContext*",
        "SparkScene*": "SparkScene*",
        "SparkInput*": "SparkInput*",
        "SparkCamera2D*": "SparkCamera2D*",
        "char*": "sbyte*",
        "char*const*": "sbyte**",
        "const char*": "sbyte*",
        "const char* const*": "sbyte**",
    }
    if c in table:
        return table[c]
    if c.endswith("*"):
        return c.replace(" ", "")
    return "int"


def parse_params(args: str) -> str:
    if not args.strip():
        return ""
    parts = []
    for raw in args.split(","):
        raw = raw.strip()
        if not raw:
            continue
        if " " not in raw:
            parts.append(f"{map_type(raw)} arg")
            continue
        typ, name = raw.rsplit(" ", 1)
        if name in {"object", "const", "out", "in"}:
            name = f"@{name}"
        parts.append(f"{map_type(typ)} {name}")
    return ", ".join(parts)


def existing_native_exports() -> set[str]:
    native = ROOT / "scripting/bindings/generated/Spark.Bindings/Native.g.cs"
    if not native.is_file():
        return set()
    body = native.read_text(encoding="utf-8")
    return set(re.findall(r"\b(spark_\w+)\s*\(", body))


def interop_header_text() -> str:
    text = HDR.read_text(encoding="utf-8")
    if HDR_GENERATED.is_file():
        text += "\n" + HDR_GENERATED.read_text(encoding="utf-8")
    return text


def main() -> int:
    text = re.sub(r"\s+", " ", interop_header_text())
    existing = existing_native_exports()
    lines = [
        "// <auto-generated /> — companion P/Invoke from SparkInterop.h",
        "#nullable enable",
        "using System.Runtime.InteropServices;",
        "",
        "namespace Spark.Bindings;",
        "",
        "public static unsafe partial class Native",
        "{",
    ]
    count = 0
    for m in DECL_RE.finditer(text):
        name = m.group("name")
        if name in existing or name.startswith("spark_script_host"):
            continue
        ret = map_type(m.group("ret").strip())
        sig = parse_params(m.group("args"))
        lines.append('    [DllImport("SparkInterop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]')
        lines.append(f"    public static extern {ret} {name}({sig});")
        lines.append("")
        count += 1
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({count} imports)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
