#!/usr/bin/env bash
# Regenerates SparkComponentKind.g.cs from SparkInteropComponentKinds.h (run after enum changes).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HDR="$ROOT/include/spark/scripting/SparkInteropComponentKinds.h"
OUT="$ROOT/scripting/bindings/generated/Spark.Bindings/SparkComponentKind.g.cs"

{
  echo "// <auto-generated /> — from SparkInteropComponentKinds.h. Do not edit."
  echo "#nullable enable"
  echo ""
  echo "namespace Spark.Bindings;"
  echo ""
  echo "public enum SparkComponentKind : uint"
  echo "{"
  grep 'SparkComponentKind_' "$HDR" | sed 's/^/    /'
  echo "}"
} > "$OUT"

echo "Wrote $OUT"
